// DNA-emitted CopilotKit runtime route for memory-agent.
//
// Generated by DNA's frontend emit (copilot case). This App-Router endpoint
// bridges the browser to the emitted `/agui` backend via an AG-UI `HttpAgent`.
// The per-runtime resume behaviour lives in `resume-adapter.ts` (agno resumes
// natively; MS Agent Framework rewrites the resume payload) — this route stays
// runtime-agnostic. Never hand-edit: change the Copilot in DNA and re-emit.
import { CopilotRuntime, createCopilotRuntimeHandler } from "@copilotkit/runtime/v2";

import { buildAgent } from "@/lib/copilot/resume-adapter";

// The emitted AG-UI backend. `DNA_BACKEND_URL` points at the servable copilot
// app (`uvicorn memory_agent_serve:app`); the agent is mounted at POST /agui.
const BACKEND = process.env.DNA_BACKEND_URL ?? "http://localhost:8000";
const AGENT_URL = process.env.DNA_AGENT_URL ?? `${BACKEND}/agui`;

// `default` is required — the v2 client falls back to it when a ready-made
// component mounts without an explicit agentId. Both point at the one mounted
// agent; memory-agent is also reachable by its explicit id.
const runtime = new CopilotRuntime({
  agents: {
    default: buildAgent(AGENT_URL),
    "memory-agent": buildAgent(AGENT_URL),
  },
});

const handler = createCopilotRuntimeHandler({
  runtime,
  basePath: "/api/copilotkit",
});

export const GET = handler;
export const POST = handler;
export const OPTIONS = handler;
