"""DNA-emitted Microsoft Agent Framework copilot serving app: memory-agent.

Generated by `dna emit --target agent-framework` (copilot case). Serves the
mounted agent over the AG-UI protocol at `/agui` via
`add_agent_framework_fastapi_endpoint`. Run it with any ASGI server, e.g.
`uvicorn memory_agent_serve:app`.
"""
from fastapi import FastAPI, Request

from agent_framework_ag_ui import add_agent_framework_fastapi_endpoint
from memory_agent import build_agent
from memory_agent import (
    reset_request_tenant,
    set_request_tenant,
    tenant_from_headers,
)
app = FastAPI()


@app.middleware("http")
async def _derive_tenant(request: Request, call_next):
    """Derive the per-run DNA tenant/oid from inbound request headers into the
    request-scoped ContextVar the MCP header_provider reads (the inbound->outbound
    tenant bridge — NOT a propagate_tenant freebie)."""
    token = set_request_tenant(tenant_from_headers(request.headers))
    try:
        return await call_next(request)
    finally:
        reset_request_tenant(token)


#: The mounted agent, served at `/agui` (the AG-UI protocol). `uvicorn
#: memory_agent_serve:app` runs it.
add_agent_framework_fastapi_endpoint(
    app,
    agent=build_agent(),
    path="/agui",
)
