"""DNA-emitted Foundry hosted agent: memory-agent (hosting.mode=hosted, target=foundry).

Generated by `dna emit` (hosting case). Packages the mounted agent as a Foundry
*hosted agent*: a container that serves the Responses protocol on 8088 via
`agent_framework_foundry_hosting.ResponsesHostServer`, invoked through the Foundry
gateway. INSTRUCTIONS is the DNA-composed prompt (Soul + guardrails + instruction),
carried byte-equal — edit the agent in DNA and re-emit, never hand-edit it here.

DEGRADED single-identity variant (design §2). This is the HOSTED sibling of the
self-hosted AG-UI app: `hosting.mode` is a variant selector over ONE agent def.
The hosted variant DROPS the per-user concerns that don't fit the hosted
single-identity, request/response model:
  - per-user OBO — auth is the platform-injected AGENT identity
    (`DefaultAzureCredential`), not the signed-in user;
  - HITL approval — the MCP mount carries NO `approval_mode` (no approval card),
    write tools run under the agent identity;
  - per-user long-term memory — Foundry hosting manages conversation history.
Emit the self-hosted variant (`hosting.mode: self-hosted`) for the per-user
AG-UI app that keeps OBO / HITL / per-user memory. Config comes from env, injected
by the platform (f-copilot-infra-binding wires the infra refs → env vars).
"""
import os

from agent_framework import Agent
from agent_framework.foundry import FoundryChatClient
from agent_framework_foundry_hosting import ResponsesHostServer
from azure.identity import DefaultAzureCredential
from agent_framework import MCPStreamableHTTPTool
from agent_framework.postgres import PostgresVectorStore
INSTRUCTIONS = "Remember and recall the user's notes. Confirm before writing.\n\nYou are the Helpdesk Concierge, an internal engineering support assistant. You help developers triage and resolve engineering questions."

def _mcp_tools() -> list[MCPStreamableHTTPTool]:
    """The DNA MCP server(s) this hosted agent mounts over Streamable HTTP. The
    DEGRADE: no `approval_mode` (HITL stripped) and no `header_provider` (per-user
    OBO/tenant stripped) — a single service identity. `allowed_tools` still bounds
    what the model may call; tool bodies live on the remote MCP server."""
    return [
        MCPStreamableHTTPTool(
            name='mcp_dna-mcp',
            url='https://mcp.dna.example/agui',
            allowed_tools=['forget', 'recall', 'remember'],
        ),
    ]



def _vector_store() -> PostgresVectorStore:
    """The single-identity RAG grounding that SURVIVES the degrade (`Copilot.
    knowledge`): shared-corpus retrieval, not per-user memory. Binds MS-AF's
    `PostgresVectorStore` — the DSN comes from the `primary-pg` infra ref via its
    env var (f-copilot-infra-binding wires it), NEVER a hardcoded literal. Load the
    corpus CONTENT per-app."""
    return PostgresVectorStore(
        collection_name='knowledge_base',
        connection_string=os.environ["DNA_PRIMARY_PG_URL"],
        embedding_model='text-embedding-3-small',
        embedding_dimensions=1536,
    )


def build_agent() -> Agent:
    """Build the hosted MS Agent Framework agent — a Foundry-backed ChatAgent under
    the platform-injected agent identity (`FoundryChatClient(...).as_agent(...)`)."""
    client = FoundryChatClient(
        model='azure/gpt-4o',
        credential=DefaultAzureCredential(),
    )
    return client.as_agent(
        name='memory-agent',
        instructions=INSTRUCTIONS,
        tools=_mcp_tools(),
        context_providers=[_vector_store()],
    )


def main() -> None:
    """Serve the agent over the Responses protocol on 8088. `ResponsesHostServer`
    is the bridge — it serves any agent over /responses for the Foundry gateway."""
    ResponsesHostServer(build_agent()).run()


if __name__ == "__main__":
    main()
