"""DNA-emitted Agno copilot serving app: memory-agent.

Generated by `dna emit --target agno` (copilot case). Serves the mounted agent
over the AG-UI protocol at `/agui` via Agno's AgentOS. Run it with any ASGI
server, e.g. `uvicorn memory_agent_serve:app`.

AgentOS mounts the `AGUI` interface; the mounted agent is built once here via the
sibling module's `build_agent` factory.
"""
from __future__ import annotations

from agno.os import AgentOS
from agno.os.interfaces.agui import AGUI

from memory_agent import build_agent

agent = build_agent()

agent_os = AgentOS(agents=[agent], interfaces=[AGUI(agent=agent)])

#: The ASGI app — `uvicorn memory_agent_serve:app`. The AG-UI router is served
#: at `/agui` (POST run, GET status).
app = agent_os.get_app()
