"""``dna.application`` — the DNA transport-agnostic application / use-case layer.

Per ``adr-faces-reorg`` (move #1, load-bearing): the shared ``*_impl`` use-cases
that the three DNA faces (CLI, MCP server, REST API) call live HERE, in the core,
so a face is a thin adapter over them — never a re-implementation and never a home
for business logic. Each use-case takes a :class:`LiveDna` handle and drives the
kernel directly; nothing here imports HTTP / Click / FastMCP.

Faces boot a ``LiveDna`` (the CLI's ``boot_live`` composition root) and delegate:
the MCP server (``dna_cli._mcp_server``) and the REST API (``dna_cli._rest_api``)
both import these use-cases and only translate transport + edge validation
(auth/quota, request/response shaping, JSON-RPC).
"""
from dna.application.live import LiveDna
from dna.application.sdlc import (
    InvalidTransition,
    add_comment,
    comment_impl,
    create_feature,
    create_feature_impl,
    create_issue,
    create_issue_impl,
    create_story,
    create_story_impl,
    set_status,
    set_status_impl,
)
from dna.application.runtime import (
    BoardItemNotFound,
    MemberForbidden,
    MemberNotFound,
    ProjectNotFound,
    WorkspaceForbidden,
    WorkspaceLastOwner,
    WorkspaceMemberNotFound,
    accept_invites_impl,
    board_item_impl,
    board_summary_impl,
    compose_prompt_impl,
    consolidate_impl,
    forget_impl,
    get_adr_impl,
    get_project_impl,
    get_skill_impl,
    get_template_impl,
    get_tool_impl,
    import_memories_impl,
    invite_member_impl,
    list_agents_impl,
    list_skills_impl,
    list_workspace_members_impl,
    list_workspaces_impl,
    list_templates_impl,
    list_members_impl,
    list_memories_impl,
    list_orgs_impl,
    list_projects_impl,
    list_repos_impl,
    list_stories_impl,
    list_tools_impl,
    create_project_impl,
    create_workspace_impl,
    ensure_workspace_scope_genome,
    provision_tenant_owner_impl,
    provision_workspace_owner_impl,
    recall_impl,
    remember_impl,
    remove_member_impl,
    revoke_workspace_member_impl,
    set_member_impl,
    set_workspace_plan_impl,
)

__all__ = [
    "LiveDna",
    # SDLC write core (shared by the CLI + the MCP write tools)
    "InvalidTransition",
    "create_story",
    "create_issue",
    "create_feature",
    "set_status",
    "add_comment",
    "create_story_impl",
    "create_issue_impl",
    "create_feature_impl",
    "set_status_impl",
    "comment_impl",
    "compose_prompt_impl",
    "list_agents_impl",
    "list_tools_impl",
    "get_tool_impl",
    # toolkit (Spec Kit Layer 3 — PromptTemplates + Skills served live)
    "list_templates_impl",
    "get_template_impl",
    "list_skills_impl",
    "get_skill_impl",
    "list_stories_impl",
    "get_adr_impl",
    "recall_impl",
    "remember_impl",
    "consolidate_impl",
    "import_memories_impl",
    "list_memories_impl",
    "forget_impl",
    # portfolio (the DNA Cloud console read model)
    "list_orgs_impl",
    "list_projects_impl",
    "get_project_impl",
    "list_repos_impl",
    "board_summary_impl",
    "board_item_impl",
    "list_members_impl",
    "set_member_impl",
    "remove_member_impl",
    "provision_tenant_owner_impl",
    "set_workspace_plan_impl",
    # workspace invites (Model B, F3 — the identity→workspace boundary writes)
    "invite_member_impl",
    "list_workspace_members_impl",
    "accept_invites_impl",
    # workspace + project CREATION (decision D5 / A1 — the write path)
    "create_workspace_impl",
    "ensure_workspace_scope_genome",
    "list_workspaces_impl",
    "create_project_impl",
    # workspace owner bootstrap + revoke (Model B, f-ws-owner-provision)
    "provision_workspace_owner_impl",
    "revoke_workspace_member_impl",
    "WorkspaceForbidden",
    "WorkspaceLastOwner",
    "WorkspaceMemberNotFound",
    "ProjectNotFound",
    "BoardItemNotFound",
    "MemberForbidden",
    "MemberNotFound",
]
