"""``dna.application`` — the DNA transport-agnostic application / use-case layer.

Per ``adr-faces-reorg`` (move #1, load-bearing): the shared ``*_impl`` use-cases
that the three DNA faces (CLI, MCP server, REST API) call live HERE, in the core,
so a face is a thin adapter over them — never a re-implementation and never a home
for business logic. Each use-case takes a :class:`LiveDna` handle and drives the
kernel directly; nothing here imports HTTP / Click / FastMCP.

Faces boot a ``LiveDna`` (the CLI's ``boot_live`` composition root) and delegate:
the MCP server (``dna_cli._mcp_server``) and the REST API (``dna_cli._rest_api``)
both import these use-cases and only translate transport + edge validation
(auth/quota, request/response shaping, JSON-RPC).
"""
from dna.application.gates import (
    GATE_EXIT_CRITERIA,
    GATE_TEST_ON_CLOSE,
    MethodologyRefusal,
    closing_warnings,
    has_passing_product_run,
    kind_is_gated,
    refuse_close_without_tests,
    refuse_without_exit_criteria,
)
from dna.application.live import LiveDna
from dna.application.delegation_tool import TOOL_NAME as DELEGATE_TO_TOOL_NAME
from dna.application.delegation_tool import make_delegate_tool
from dna.application.sdlc_family import (
    board_probe_order,
    dated_spec_fields,
    digest_kinds,
    filed_kinds,
    journey_derived_kinds,
    producer_kinds,
    rollup_kinds,
    status_enum_for,
    status_enums,
    transitionable_kinds,
    work_item_kinds,
)
from dna.application.instances import (
    AmbiguousKindError,
    BootstrapKindWriteRefused,
    ConcurrentWriteError,
    DeleteRefused,
    UnknownInstanceError,
    UnknownKindError,
    bootstrap_kinds,
    delete_instance_impl,
    delete_refusal,
    family_for_kind,
    get_instance_impl,
    resolve_instance_impl,
    graph_refs_impl,
    is_append_only_kind,
    is_bootstrap_kind,
    list_instances_impl,
    list_kinds_impl,
    resolve_kind_port,
    resolve_kind_port_live,
    spec_etag,
    write_instance_impl,
)
from dna.application.kind_authoring import (
    AuthoredKindNotFound,
    NamespaceRegistryUnreadable,
    approve_kind_impl,
    author_kind_impl,
    get_authored_kind_impl,
    list_authored_kinds_impl,
    revoke_kind_impl,
)
from dna.application.sdlc import (
    InstanceExists,
    InvalidTransition,
    add_comment,
    comment_impl,
    create_feature,
    create_feature_impl,
    create_issue,
    create_issue_impl,
    create_story,
    create_story_impl,
    refuse_if_exists,
    set_status,
    set_status_impl,
)
from dna.application.runtime import (
    BoardItemNotFound,
    MemberForbidden,
    MemberNotFound,
    ProjectNotFound,
    WorkspaceForbidden,
    WorkspaceLastOwner,
    WorkspaceMemberNotFound,
    accept_invites_impl,
    apply_definition_impl,
    board_item_impl,
    board_summary_impl,
    compose_prompt_impl,
    consolidate_impl,
    forget_impl,
    grant_workspace_scope_impl,
    get_adr_impl,
    get_project_impl,
    get_skill_impl,
    genome_view_impl,
    get_template_impl,
    get_tool_impl,
    import_memories_impl,
    invite_member_impl,
    list_agents_impl,
    list_skills_impl,
    list_workspace_members_impl,
    list_workspaces_impl,
    list_templates_impl,
    list_bundle_entries_impl,
    list_workspace_scope_grants_impl,
    list_members_impl,
    list_memories_impl,
    list_orgs_impl,
    list_projects_impl,
    workspace_owns_board_scope,
    list_repos_impl,
    list_stories_impl,
    list_tools_impl,
    adopt_workspace_scope_on_access,
    create_project_impl,
    register_artifact_impl,
    create_workspace_impl,
    ensure_workspace_scope_genome,
    provision_tenant_owner_impl,
    provision_workspace_owner_impl,
    read_bundle_entry_impl,
    read_definition_impl,
    kind_graph_impl,
    read_registered_kind_impl,
    recall_impl,
    reconcile_forks_impl,
    remember_impl,
    revoke_workspace_scope_impl,
    remove_member_impl,
    revert_bundle_entry_impl,
    revert_definition_impl,
    revoke_workspace_member_impl,
    set_member_impl,
    set_account_plan_impl,
    workspace_granted_scopes,
    write_bundle_entry_impl,
)

__all__ = [
    "LiveDna",
    # delegate_to — the tool a team_members declarer gets (s-close-the-two-doors
    # Peça A). Importing this module is cheap (langchain/pydantic are deferred
    # INSIDE make_delegate_tool); only calling it requires the [runtime] extra.
    "DELEGATE_TO_TOOL_NAME",
    "make_delegate_tool",
    # generic, registry-driven instance CRUD (s-mcp-generic-instance-tools) —
    # the ONE path any face serves "every Kind" through, instead of N
    # hand-written per-Kind tools.
    "list_kinds_impl",
    "list_instances_impl",
    "get_instance_impl",
    "resolve_instance_impl",
    "graph_refs_impl",
    "write_instance_impl",
    "resolve_kind_port",
    "resolve_kind_port_live",
    "spec_etag",
    "DeleteRefused",
    "UnknownInstanceError",
    "delete_instance_impl",
    "delete_refusal",
    "is_append_only_kind",
    "family_for_kind",
    "grant_workspace_scope_impl",
    "list_workspace_scope_grants_impl",
    "revoke_workspace_scope_impl",
    "workspace_granted_scopes",
    "GATE_EXIT_CRITERIA",
    "GATE_TEST_ON_CLOSE",
    "MethodologyRefusal",
    "board_probe_order",
    "closing_warnings",
    "dated_spec_fields",
    "digest_kinds",
    "filed_kinds",
    "has_passing_product_run",
    "journey_derived_kinds",
    "kind_is_gated",
    "producer_kinds",
    "refuse_close_without_tests",
    "refuse_without_exit_criteria",
    "rollup_kinds",
    "status_enum_for",
    "status_enums",
    "transitionable_kinds",
    "work_item_kinds",
    "bootstrap_kinds",
    "is_bootstrap_kind",
    "AmbiguousKindError",
    "BootstrapKindWriteRefused",
    "ConcurrentWriteError",
    "UnknownKindError",
    # Kind authoring — the dedicated door (writes an INERT KindDefinition)
    "AuthoredKindNotFound",
    "NamespaceRegistryUnreadable",
    "approve_kind_impl",
    "author_kind_impl",
    "get_authored_kind_impl",
    "list_authored_kinds_impl",
    "revoke_kind_impl",
    # SDLC write core (shared by the CLI + the MCP write tools)
    "InstanceExists",
    "InvalidTransition",
    "refuse_if_exists",
    "create_story",
    "create_issue",
    "create_feature",
    "set_status",
    "add_comment",
    "create_story_impl",
    "create_issue_impl",
    "create_feature_impl",
    "set_status_impl",
    "comment_impl",
    "compose_prompt_impl",
    "list_agents_impl",
    "list_tools_impl",
    "get_tool_impl",
    "genome_view_impl",
    # definitions: read/apply/revert a tenant-layer override (s-strain-customization-ui)
    "read_definition_impl",
    # o descritor do Kind REGISTRADO (schema + ui_schema) — formulários derivam
    "read_registered_kind_impl",
    # o GRAFO de schema do registry inteiro, numa chamada (fatia 1 do degrau 1)
    "kind_graph_impl",
    "apply_definition_impl",
    "revert_definition_impl",
    # bundle entries: list/read/write/revert a bundle-file fork (plane B — s-strain-bundle-fork)
    "list_bundle_entries_impl",
    "read_bundle_entry_impl",
    "write_bundle_entry_impl",
    "revert_bundle_entry_impl",
    "reconcile_forks_impl",
    # toolkit (Spec Kit Layer 3 — PromptTemplates + Skills served live)
    "list_templates_impl",
    "get_template_impl",
    "list_skills_impl",
    "get_skill_impl",
    "list_stories_impl",
    "get_adr_impl",
    "recall_impl",
    "remember_impl",
    "consolidate_impl",
    "import_memories_impl",
    "list_memories_impl",
    "forget_impl",
    # portfolio (the DNA Cloud console read model)
    "list_orgs_impl",
    "list_projects_impl",
    "workspace_owns_board_scope",
    "get_project_impl",
    "list_repos_impl",
    "board_summary_impl",
    "board_item_impl",
    "list_members_impl",
    "set_member_impl",
    "remove_member_impl",
    "provision_tenant_owner_impl",
    "set_account_plan_impl",
    # workspace invites (Model B, F3 — the identity→workspace boundary writes)
    "invite_member_impl",
    "list_workspace_members_impl",
    "accept_invites_impl",
    # workspace + project CREATION (decision D5 / A1 — the write path)
    "create_workspace_impl",
    "ensure_workspace_scope_genome",
    "adopt_workspace_scope_on_access",
    "list_workspaces_impl",
    "create_project_impl",
    "register_artifact_impl",
    # workspace owner bootstrap + revoke (Model B, f-ws-owner-provision)
    "provision_workspace_owner_impl",
    "revoke_workspace_member_impl",
    "WorkspaceForbidden",
    "WorkspaceLastOwner",
    "WorkspaceMemberNotFound",
    "ProjectNotFound",
    "BoardItemNotFound",
    "MemberForbidden",
    "MemberNotFound",
]
