"""DNA-emitted Agno AgentOS app: ao-copilot (hosting.mode=hosted, target=agentos).

Generated by `dna emit` (hosting case). Agno AgentOS has NO managed runtime, so
"hosted" for agentos ≈ self-host (this app + compose.yaml) + an optional
control-plane REGISTRATION step (design §2/§6). INSTRUCTIONS is the DNA-composed
prompt, carried byte-equal. Run it with `python main.py` (serves on 7777).
"""
from agno.agent import Agent
from agno.os import AgentOS

INSTRUCTIONS = 'Answer.'


def build_agent() -> Agent:
    """Build the AgentOS-served agent (single-service JWT identity)."""
    return Agent(
        name='ao-copilot',
        model='azure/gpt-4o',
        instructions=INSTRUCTIONS,
    )


agent = build_agent()
agent_os = AgentOS(agents=[agent])
app = agent_os.get_app()


if __name__ == "__main__":
    # AgentOS serves the REST / AG-UI surface on 7777.
    agent_os.serve(app="main:app", port=7777)
