"""Lockfile v3 — single flat document list with origin tracking."""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from dna.kernel.document import Document


@dataclass
class LockEntry:
    """One document in the lockfile."""
    name: str
    kind: str
    api_version: str
    origin: str
    path: str
    sha256: str

    @classmethod
    def from_document(cls, doc: Document, origin: str, path: str, sha256: str) -> LockEntry:
        return cls(
            name=doc.name, kind=doc.kind, api_version=doc.api_version,
            origin=origin, path=path, sha256=sha256,
        )


@dataclass
class Lockfile:
    """Complete lockfile v3."""
    scope: str = ""
    documents: list[LockEntry] = field(default_factory=list)
    lock_version: int = 3
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


def write_lockfile(lock: Lockfile, path: Path) -> None:
    sorted_docs = sorted(lock.documents, key=lambda d: (d.kind, d.name))
    data: dict[str, Any] = {
        "lockVersion": lock.lock_version,
        "generated_at": lock.generated_at,
        "scope": lock.scope,
        "documents": [
            {
                "name": d.name,
                "kind": d.kind,
                "apiVersion": d.api_version,
                "origin": d.origin,
                "path": d.path,
                "sha256": d.sha256,
            }
            for d in sorted_docs
        ],
    }
    path.write_text(
        f"# Generated by dna install — DO NOT EDIT\n"
        f"{yaml.dump(data, default_flow_style=False, sort_keys=False)}"
    )


def read_lockfile(path: Path) -> Lockfile:
    if not path.exists():
        return Lockfile()
    data = yaml.safe_load(path.read_text())
    if not data or "documents" not in data:
        return Lockfile()
    documents = [
        LockEntry(
            name=d["name"], kind=d["kind"], api_version=d.get("apiVersion", ""),
            origin=d.get("origin", "local"), path=d.get("path", ""),
            sha256=d.get("sha256", ""),
        )
        for d in data["documents"]
    ]
    return Lockfile(
        scope=data.get("scope", ""),
        documents=documents,
        lock_version=data.get("lockVersion", 3),
        generated_at=data.get("generated_at", ""),
    )


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def dir_sha256(directory: Path) -> str:
    h = hashlib.sha256()
    for f in sorted(directory.rglob("*")):
        if f.is_file():
            h.update(str(f.relative_to(directory)).encode())
            h.update(f.read_bytes())
    return h.hexdigest()


@dataclass
class VerifyResult:
    """Result of verifying current MI against a lockfile."""
    added: list[str]    # Docs in MI but not in lock (format: "Kind/name")
    removed: list[str]  # Docs in lock but not in MI
    changed: list[str]  # Docs with different SHA

    @property
    def ok(self) -> bool:
        return not self.added and not self.removed and not self.changed


def verify_lock(mi: Any, lock_path: Path) -> VerifyResult:
    """Compare current ManifestInstance against a lockfile."""
    import json

    lock = read_lockfile(lock_path)
    lock_map: dict[tuple[str, str], str] = {
        (e.kind, e.name): e.sha256 for e in lock.documents
    }

    current_map: dict[tuple[str, str], str] = {}
    for d in mi.documents:
        raw_json = json.dumps(d.raw, sort_keys=True, ensure_ascii=False)
        sha = hashlib.sha256(raw_json.encode()).hexdigest()
        current_map[(d.kind, d.name)] = sha

    added = [f"{k}/{n}" for (k, n) in current_map if (k, n) not in lock_map]
    removed = [f"{k}/{n}" for (k, n) in lock_map if (k, n) not in current_map]
    changed = [
        f"{k}/{n}"
        for (k, n), sha in current_map.items()
        if (k, n) in lock_map and lock_map[(k, n)] != sha
    ]

    return VerifyResult(added=added, removed=removed, changed=changed)
