"""DNA-emitted LangGraph copilot serving app: memory-agent.

Generated by `dna emit --target langgraph` (copilot case). Serves the mounted
agent over the AG-UI protocol at `/agui` via the AG-UI LangGraph adapter
(the CopilotKit CoAgent serving). Run it with any ASGI server, e.g.
`uvicorn memory_agent_serve:app`.
"""
from fastapi import FastAPI, Request

from ag_ui_langgraph import LangGraphAgent, add_langgraph_fastapi_endpoint
from memory_agent import build_agent
from memory_agent import (
    reset_request_tenant,
    set_request_tenant,
    tenant_from_headers,
)
app = FastAPI()


@app.middleware("http")
async def _derive_tenant(request: Request, call_next):
    """Derive the per-run DNA tenant/oid from inbound request headers into the
    request-scoped carrier the graph seeds into `state['tenant']` and the MCP client
    stamps outbound (the inbound->outbound tenant bridge — NOT a propagate_tenant
    freebie)."""
    token = set_request_tenant(tenant_from_headers(request.headers))
    try:
        return await call_next(request)
    finally:
        reset_request_tenant(token)


#: The mounted agent, exposed at `/agui` (the AG-UI protocol). `uvicorn
#: memory_agent_serve:app` runs it.
add_langgraph_fastapi_endpoint(
    app,
    agent=LangGraphAgent(name="memory-agent", graph=build_agent()),
    path="/agui",
)
