"""H5 — Kind base class with sensible defaults.

Cuts the 19-mandatory + 8-optional attribute boilerplate that every
Kind implementation duplicated. Subclassing pattern:

    class AssetKind(KindBase):
        api_version = "github.com/ruinosus/dna/asset/v1"
        kind = "Asset"
        alias = "asset-asset"
        storage = StorageDescriptor.bundle("assets", "ASSET.md")
        ascii_icon = "🖼️"
        display_label = "Assets"

That's the minimum-viable Kind. Everything else inherits sensible
defaults from this base.

The base is **purely additive**: existing 43 Kind impls keep working
as plain classes (they declare every attribute explicitly). Migrating
a Kind to ``KindBase`` is a strict simplification — no API changes
are forced.

Because Python's ``@runtime_checkable`` Protocol uses structural
typing, a ``KindBase`` subclass that only sets ``kind`` + ``alias``
+ ``storage`` still satisfies ``isinstance(obj, KindPort)`` at boot
time (H1 validation passes) — every required attr/method is provided
by the base class.

Mandatory overrides (no default available):
  - ``api_version``    — globally unique namespace string
  - ``kind``           — CamelCase Kind name
  - ``alias``          — globally unique alias
  - ``storage``        — StorageDescriptor.{bundle,yaml,root}(...)

Everything else has defaults that match the most common case.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any


class KindBase:
    """Default-providing base for KindPort implementations.

    NOT a dataclass: KindPort's `model: type` and other class-level
    attributes interact poorly with @dataclass field generation. Plain
    class inheritance is cleaner. Subclasses override what they need;
    everything else falls through to these defaults.
    """

    # ---- Identity (3 of these MUST be overridden by subclasses) -----
    # api_version: str — REQUIRED override; e.g. "github.com/ruinosus/dna/asset/v1"
    # kind: str        — REQUIRED override; e.g. "Asset"
    # alias: str       — REQUIRED override; e.g. "asset-asset"
    # storage: StorageDescriptor — REQUIRED override
    model: type = dict
    origin: str | None = None

    # ---- Source-sync identity (s-sync-s1) ---------------------------
    # Spec fields that are write-/runtime-stamped, NOT part of the doc's
    # authored identity. Excluded from canonical_digest so the same doc
    # in two sources (FS git ↔ Postgres runtime) hashes identically even
    # when one was stamped on write. Kinds override to extend (e.g. an
    # EvalRun adds 'completed_at', a StatusReport adds 'generated_at').
    VOLATILE_SPEC_FIELDS: frozenset[str] = frozenset(
        {"updated_at", "version", "created_at"}
    )

    # ---- Behavior flags (sensible defaults) -------------------------
    # ``is_root`` was an explicit boolean Phase 0–15. Phase 16 derives
    # it from the storage descriptor: a Kind is the scope root iff its
    # storage pattern is ROOT (single file at scope root). GenomeKind
    # is the only one today; the property keeps the existing read API
    # (``kp.is_root``) working for all consumers.
    is_prompt_target: bool = False
    prompt_target_priority: int = 0
    flatten_in_context: bool = False

    @property
    def is_root(self) -> bool:
        from dna.kernel.protocols import StoragePattern
        storage = getattr(self, "storage", None)
        return getattr(storage, "pattern", None) == StoragePattern.ROOT
    # See KindPort.is_runtime_artifact in protocols.py. Override to
    # ``True`` only on Kinds whose documents are generated by runtime
    # workflows (EvalRun, Finding, Evidence, AssessmentRun, ...).
    is_runtime_artifact: bool = False

    # ---- Two-planes (spec 2026-06-09-kinds-two-planes-design) -------
    # ``plane`` declares which storage/cache plane this Kind belongs to:
    #   "composition" (default) — participates in agent composition; reads
    #       go through the ManifestInstance; writes invalidate scope caches.
    #   "record" — pure typed document (Story, EvalRun, WorkflowEvent, ...);
    #       writes/deletes NEVER trigger a scope reload (only the O(1)
    #       per-doc L2 drop + write event). See D1/D3 of the spec.
    # Explicit, never derived — kernel.kind() lints contradictions
    # (plane="record" with prompt-target/root/schema-affecting signals).
    plane: str = "composition"

    # ---- Kernel classification (s-kernel-kindport-classification-attrs) ----
    # These replace the kernel's hardcoded Kind-name frozensets — the Kernel
    # now DERIVES its classification sets from these per-Kind attributes instead
    # of matching strings. Defaults match the common case; the handful of Kinds
    # that differ override them.
    #
    # ``is_schema_affecting``: writing a doc of this Kind invalidates the
    # kernel's schema cache (Kinds that contribute to prompt/agent composition
    # schema). Was ``Kernel._SCHEMA_INVALIDATING_KINDS``.
    is_schema_affecting: bool = False
    # ``is_overlayable``: a tenant overlay may fork this Kind. False only for the
    # structural bootstrap Kinds (scope identity / schema / policy). Was the
    # negation of ``Kernel._NON_OVERLAYABLE_KINDS``.
    is_overlayable: bool = True
    # ``scope_inheritable``: documents of this Kind inherit across scopes by
    # default. False for the per-scope SDLC ledger + structural Kinds. Was the
    # negation of ``Kernel._NON_INHERITABLE_KINDS``.
    scope_inheritable: bool = True
    # ``is_catalog_identity``: writing a doc of this Kind changes the Catalog
    # tier's scope/mandatory set for every tenant, so the kernel drops its
    # internal catalog cache after the write (s-write-path-despecialize —
    # was a hardcoded ``kind == "Genome"`` check in write_document). True
    # only on the scope-root identity Kind (GenomeKind).
    is_catalog_identity: bool = False

    # ---- Embedding source fields (F3 spec D4) ------------------------
    # Fields of ``spec`` that compose the doc's embedding text. None =
    # not embeddable (or still covered by the legacy EMBEDDABLE_KINDS
    # frozenset in harness-shared). Declared here so the D4 derivation
    # covers still-class Kinds as well as descriptor-synthesized ports.
    embed_fields: list[str] | None = None

    # ---- Optional presentation surface (KindPresentation) ----------
    # Typed home: dna.kernel.protocols.KindPresentation — the
    # capability Protocol for the optional UX/rendering members. These
    # defaults let any KindBase subclass opt in field-by-field.
    # (`preview()`/`graph_meta()` deliberately have NO default here:
    # their ABSENCE is meaningful — consumers fall back to the generic
    # renderer when getattr(kp, "preview", None) is None.)
    docs: str | None = None
    description_fallback_field: str | None = None
    graph_style: dict | None = None
    ascii_icon: str | None = None
    display_label: str | None = None
    ui_schema: dict | None = None
    # Explicit backend-visibility override; None → the storage-pattern
    # default (see protocols.resolve_visible_in_backend).
    visible_in_backend: bool | None = None

    # ---- Studio UI manifest metadata (Phase 2 — 2026-05-16) ---------
    # When populated, Studio's `GET /kinds/manifest` serializes this
    # field and the Studio TS-side merger picks it up to generate
    # routes + sidebar entries + sitemap rows automatically.
    #
    # None = the Kind exists in the system but is invisible in Studio
    # (back-compat with the ~30 Kinds that haven't been migrated to
    # the manifest yet).
    #
    # See dna.kernel.studio_ui.StudioUIMetadata for the
    # dataclass + field documentation.
    ui: Any = None  # StudioUIMetadata | None — typed as Any to avoid forced import

    # ---- H1 opt-in for shared bundle markers -----------------------
    marker_shared_allowed: bool = False

    # ---- Validation (s-typed-models-for-dict-kinds) -----------------
    # When True, ``parse()`` validates the doc's ``spec`` against ``schema()``
    # (jsonschema) before returning — so model=dict Kinds get real validation
    # instead of trusting every field (the i-082 ``.spec crash`` class). An
    # invalid doc raises a clear ``jsonschema.ValidationError``; the kernel's
    # ``_parse_doc`` catches it → ``typed=None`` + a ``parse_error`` event (the
    # doc still loads, untyped), so turning this on never crashes a load.
    # Opt-in (default False) keeps the ~70 non-runtime Kinds unchanged.
    validate_on_parse: bool = False

    # ---- Behavior methods (default implementations) ----------------

    def dep_filters(self) -> dict[str, str] | None:
        """Cross-Kind references by alias. Default: no deps."""
        return None

    def dependencies(self) -> dict[str, str] | None:
        """Clearer name for ``dep_filters``. Defaults to delegating."""
        return self.dep_filters()

    def schema(self) -> dict[str, Any] | None:
        """JSON Schema for the spec dict. Default: no schema."""
        return None

    def get_default_agent_name(self, doc: Any) -> str | None:
        """Which agent (Agent) owns documents of this Kind."""
        del doc
        return None

    def get_layer_policies(self, doc: Any) -> dict | None:
        """Per-layer write policies (OPEN / RESTRICTED / LOCKED)."""
        del doc
        return None

    def parse(self, raw: dict[str, Any]) -> Any:
        """Convert raw dict → typed model. Default: pass-through dict.

        Override to instantiate a Pydantic model or dataclass —
        ``self.model(**raw)`` is the typical impl.

        When ``validate_on_parse`` is set, the doc's ``spec`` is first validated
        against ``schema()`` (s-typed-models-for-dict-kinds) — a clear
        ``jsonschema.ValidationError`` is raised for a malformed doc.
        """
        if self.validate_on_parse:
            self._validate_spec(raw)
        return raw

    def _validate_spec(self, raw: dict[str, Any]) -> None:
        """Validate the doc's spec against ``schema()`` (no-op if no schema).

        Accepts both shapes (mirrors the gaia Kinds' defensive parse): a full
        envelope ``{apiVersion, kind, spec: {...}}`` validates ``raw['spec']``;
        a flat dict (the spec fields at the root) validates the dict itself.
        """
        schema = self.schema()
        if schema is None:
            return
        import jsonschema  # local import — only loaded when a Kind opts in
        if isinstance(raw, dict) and "apiVersion" in raw and isinstance(raw.get("spec"), dict):
            spec = raw["spec"]
        else:
            spec = raw or {}
        jsonschema.validate(spec, schema)

    def describe(self, doc: Any) -> str | None:
        """One-liner human description for tree views and lists."""
        del doc
        return None

    def summary(self, doc: Any) -> dict[str, Any] | None:
        """Compact metadata projection for list endpoints. Default:
        return the whole spec dict (works for small specs)."""
        spec = getattr(doc, "spec", None) or {}
        if isinstance(spec, dict):
            return dict(spec)
        return None

    def prompt_template(self) -> str | None:
        """Mustache/Jinja template for prompt context inclusion.
        Default: no template (Kind contributes nothing to prompts)."""
        return None

    def layout_template(self, name: str) -> str | None:
        """Resolve a NAMED composition layout to an embedded template
        (s-dx-named-layouts).

        Prompt-target Kinds override this to expose author-friendly layout
        presets (e.g. ``persona-first``, ``instruction-first``) so the common
        case never hand-writes Mustache. Returns ``None`` for an unknown name
        (the prompt builder fails loud). Default: no named layouts."""
        return None

    def layout_names(self) -> list[str]:
        """Public layout names this Kind offers (s-dx-named-layouts).

        Powers discovery + fail-loud error messages + ``dna new --layout``
        validation. Default: none."""
        return []

    # ---- Source-sync digest (s-sync-s1) -----------------------------

    def _canonical_spec(self, spec: dict[str, Any]) -> dict[str, Any]:
        """Normalize a spec for hashing: drop volatile + transport fields and
        fold a resolved ``instruction_file`` into its inline body, so the digest
        reflects authored CONTENT, not storage form. Override-friendly hook."""
        out = {
            k: v for k, v in (spec or {}).items()
            if k not in self.VOLATILE_SPEC_FIELDS
        }
        # `source_files` is pure transport (bundle entries ride here on apply);
        # never part of identity. The fragment's CONTENT lives in `instruction`.
        out.pop("source_files", None)
        # When an instruction_file was resolved, the body is in `instruction`;
        # drop the pointer so file-backed and inline authoring hash the same.
        if out.get("instruction_file") and out.get("instruction"):
            out.pop("instruction_file", None)
        return out

    def canonical_digest(self, doc: Any) -> str:
        """Stable SHA-256 of the doc's authored identity — the basis for
        source diff/sync (s-sync). Two docs that are semantically identical
        hash the same regardless of key order, comments, formatting, volatile
        stamps (updated_at/version/created_at), or whether the instruction was
        authored inline vs via instruction_file.

        kind + name + canonical(spec). Canonical JSON = sorted keys, compact
        separators, so logically-equal objects always serialize identically.
        """
        spec = getattr(doc, "spec", None)
        spec = dict(spec) if spec else {}
        payload = {
            "kind": getattr(doc, "kind", None) or self.kind,
            "name": getattr(doc, "name", None),
            "spec": self._canonical_spec(spec),
        }
        canonical = json.dumps(
            payload, sort_keys=True, separators=(",", ":"), default=str,
            ensure_ascii=False,
        )
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
