/**
 * Lockfile types and utilities — snapshot of resolved documents.
 *
 * 1:1 parity with Python lockfile structures.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { sha256 } from "js-sha256";
import yaml from "js-yaml";

export interface LockEntry {
  name: string;
  kind: string;
  apiVersion: string;
  origin: string;
  path: string;
  sha256: string;
}

export interface Lockfile {
  scope: string;
  documents: LockEntry[];
  lockVersion: number;
  generatedAt: string;
}

export interface VerifyResult {
  added: string[];    // "Kind/name" in MI but not in lock
  removed: string[];  // in lock but not in MI
  changed: string[];  // different SHA
  ok: boolean;
}

/**
 * Serialize a value to JSON matching Python's json.dumps(sort_keys=True, ensure_ascii=False).
 *
 * Key differences from JSON.stringify:
 * - Object keys are recursively sorted (not just top-level)
 * - Separators use spaces: ", " between items and ": " between key-value pairs
 *   (Python's default separators)
 *
 * IMPORTANT: We cannot use JSON.stringify + regex replace because that would
 * corrupt colons and commas inside string values (e.g., URLs like "http://host:8080").
 * Python's json.dumps only adds spaces around STRUCTURAL separators, never inside strings.
 */
function pythonJsonDumps(obj: unknown): string {
  if (obj === null) return "null";
  if (typeof obj === "boolean") return obj ? "true" : "false";
  if (typeof obj === "number") return JSON.stringify(obj);
  if (typeof obj === "string") return JSON.stringify(obj);
  if (Array.isArray(obj)) {
    return "[" + obj.map(pythonJsonDumps).join(", ") + "]";
  }
  // Object with sorted keys
  const keys = Object.keys(obj as Record<string, unknown>).sort();
  const pairs = keys.map(
    (k) => JSON.stringify(k) + ": " + pythonJsonDumps((obj as Record<string, unknown>)[k])
  );
  return "{" + pairs.join(", ") + "}";
}

/**
 * Compute SHA-256 hash of a document's raw dict.
 *
 * Matches Python's: hashlib.sha256(json.dumps(raw, sort_keys=True, ensure_ascii=False).encode()).hexdigest()
 */
export function documentHash(raw: Record<string, unknown>): string {
  const canonical = pythonJsonDumps(raw);
  return sha256(canonical);
}

export function writeLockfile(lock: Lockfile, path: string): void {
  const sorted = [...lock.documents].sort((a, b) =>
    a.kind === b.kind ? a.name.localeCompare(b.name) : a.kind.localeCompare(b.kind)
  );
  const data = {
    lockVersion: lock.lockVersion,
    generated_at: lock.generatedAt,
    scope: lock.scope,
    documents: sorted.map(d => ({
      name: d.name,
      kind: d.kind,
      apiVersion: d.apiVersion,
      origin: d.origin,
      path: d.path,
      sha256: d.sha256,
    })),
  };
  const content = `# Generated by dna install — DO NOT EDIT\n${yaml.dump(data, { sortKeys: false })}`;
  writeFileSync(path, content);
}

export function readLockfile(path: string): Lockfile {
  if (!existsSync(path)) return { scope: "", documents: [], lockVersion: 3, generatedAt: "" };
  const raw = yaml.load(readFileSync(path, "utf-8")) as Record<string, unknown> | null;
  if (!raw || !Array.isArray(raw.documents)) return { scope: "", documents: [], lockVersion: 3, generatedAt: "" };
  const documents: LockEntry[] = (raw.documents as Record<string, unknown>[]).map(d => ({
    name: String(d.name ?? ""),
    kind: String(d.kind ?? ""),
    apiVersion: String(d.apiVersion ?? ""),
    origin: String(d.origin ?? "local"),
    path: String(d.path ?? ""),
    sha256: String(d.sha256 ?? ""),
  }));
  return {
    scope: String(raw.scope ?? ""),
    documents,
    lockVersion: Number(raw.lockVersion ?? 3),
    generatedAt: String(raw.generated_at ?? ""),
  };
}

export function verifyLock(
  documents: { kind: string; name: string; raw: Record<string, unknown> }[],
  lockPath: string,
): VerifyResult {
  const lock = readLockfile(lockPath);
  const lockMap = new Map<string, string>();
  for (const e of lock.documents) lockMap.set(`${e.kind}\0${e.name}`, e.sha256);

  const currentMap = new Map<string, string>();
  for (const d of documents) {
    const sha = documentHash(d.raw);
    currentMap.set(`${d.kind}\0${d.name}`, sha);
  }

  const added: string[] = [];
  const removed: string[] = [];
  const changed: string[] = [];

  for (const [key, sha] of currentMap) {
    const [k, n] = key.split("\0");
    if (!lockMap.has(key)) { added.push(`${k}/${n}`); continue; }
    if (lockMap.get(key) !== sha) changed.push(`${k}/${n}`);
  }
  for (const [key] of lockMap) {
    if (!currentMap.has(key)) {
      const [k, n] = key.split("\0");
      removed.push(`${k}/${n}`);
    }
  }

  return { added, removed, changed, ok: added.length === 0 && removed.length === 0 && changed.length === 0 };
}
