"""DNA-emitted Microsoft Agent Framework copilot agent: memory-agent.

Generated by `dna emit --target agent-framework` (copilot case). INSTRUCTIONS is
the DNA-composed prompt (Soul + guardrails + instruction), carried byte-equal —
edit the agent in DNA and re-emit, never hand-edit the prompt here.

The per-run factory (`build_agent` / `build_workflow`) is what the serving layer
calls, mirroring the foundry reference's Foundry-backed `as_agent(...)` factories.
Tool bodies + any per-app retrieval (AzureAISearchContextProvider) are wired at
the consumer.
"""
import contextvars
import os

from agent_framework import Agent
from agent_framework.foundry import FoundryChatClient
from azure.identity import DefaultAzureCredential
from agent_framework import MCPStreamableHTTPTool
from agent_framework.postgres import PostgresVectorStore
INSTRUCTIONS = "Remember and recall the user's notes. Confirm before writing.\n\nYou are the Helpdesk Concierge, an internal engineering support assistant. You help developers triage and resolve engineering questions."

#: Request-scoped tenant carrier. The serving layer sets it from inbound request
#: headers; the MCP `header_provider` reads it to stamp the outbound DNA tenant
#: headers on every federated MCP call (the inbound->outbound tenant bridge — NOT
#: a propagate_tenant freebie). DNA tenancy = `tenant` (Entra tid) + `workspace`
#: (→ scope `tenant-<workspace_id>`) + `personal:<oid>` (oid server-derived) — no
#: license, no namespace.
_CURRENT_TENANT: contextvars.ContextVar[dict] = contextvars.ContextVar(
    "dna_tenant", default={}
)

#: Inbound AG-UI request headers → the per-run tenant carrier. DNA-native only,
#: server-trusted (these are set service-to-service, never by the browser).
_TENANT_HEADERS = {
    "tenant": "X-DNA-Tenant",
    "workspace": "X-DNA-Workspace",
    "oid": "X-Tenant-OID",
}


def tenant_from_headers(headers) -> dict:
    """Derive the per-run DNA tenant/oid from the inbound request headers."""
    return {key: headers.get(header) for key, header in _TENANT_HEADERS.items()}


def set_request_tenant(tenant: dict):
    """Set the request-scoped tenant (called by the serving middleware); returns
    the ContextVar reset token the middleware restores after the run."""
    return _CURRENT_TENANT.set(tenant)


def reset_request_tenant(token) -> None:
    """Restore the tenant carrier after the request (paired with set_request_tenant)."""
    _CURRENT_TENANT.reset(token)


def _tenant_header_provider(_existing: dict) -> dict:
    """Stamp the request tenant onto every federated MCP call. Reads the
    request-scoped ContextVar the serving layer set from inbound headers — the
    outbound half of DNA tenant propagation."""
    tenant = _CURRENT_TENANT.get()
    headers: dict = {}
    if tenant.get("tenant"):
        headers["X-DNA-Tenant"] = tenant["tenant"]
    if tenant.get("workspace"):
        headers["X-DNA-Workspace"] = tenant["workspace"]
    if tenant.get("oid"):
        headers["X-Tenant-OID"] = tenant["oid"]
    return headers

def _mcp_tools() -> list[MCPStreamableHTTPTool]:
    """The DNA MCP server(s) this copilot mounts over Streamable HTTP. Tool bodies
    live on the remote MCP server, not in this scaffold. `allowed_tools` bounds
    what the model may call; `approval_mode` carries the tool-level HITL —
    `always_require_approval` write tools pause for the AG-UI approval card before
    they run, reads never do (a workflow copilot gates writes at the workflow
    level instead, so it mounts with `never_require`)."""
    return [
        MCPStreamableHTTPTool(
            name="mcp_dna-mcp",
            url="https://mcp.dna.example/agui",
            allowed_tools=["forget", "recall", "remember"],
            approval_mode={"always_require_approval": ["forget", "remember"], "never_require_approval": ["recall"]},
            header_provider=_tenant_header_provider,
        ),
    ]


def _vector_store() -> PostgresVectorStore:
    """The RAG store this copilot reads (`Copilot.knowledge`). DNA declares a
    pgvector store (`knowledge.store`), so this binds MS-AF's `PostgresVectorStore`
    over Postgres — the DSN comes from the `primary-pg` infra ref via its env var
    (f-copilot-infra-binding wires it), NEVER a hardcoded literal. Wire it as the
    agent's `context_providers=[_vector_store()]` and load the corpus CONTENT
    per-app."""
    return PostgresVectorStore(
        collection_name="knowledge_base",
        connection_string=os.environ["DNA_PRIMARY_PG_URL"],
        embedding_model="text-embedding-3-small",
        embedding_dimensions=1536,
    )


def _thread_store_dsn() -> str:
    """The Postgres DSN for thread/run state, read from the `primary-pg` infra ref's
    env var (f-copilot-infra-binding wires it). DNA declares Postgres checkpoint/
    memory, but MS-AF has NO native Postgres thread-store (design §6 gap): serialize
    the run's `AgentThread` (`thread.serialize()` / `AgentThread.deserialize(...)`)
    to a PG column keyed by conversation id yourself, using this DSN. This is the
    honest wiring-point — not a `PostgresSaver` equivalent."""
    return os.environ["DNA_PRIMARY_PG_URL"]

def build_agent() -> Agent:
    """Build the MS Agent Framework agent for one run — a Foundry-backed ChatAgent
    (`FoundryChatClient(...).as_agent(...)`)."""
    client = FoundryChatClient(
        model="azure/gpt-4o",
        credential=DefaultAzureCredential(),
    )
    return client.as_agent(
        name="memory-agent",
        instructions=INSTRUCTIONS,
        tools=_mcp_tools(),
        context_providers=[_vector_store()],
    )
