"""DNA-emitted Microsoft Agent Framework copilot agent: memory-agent.

Generated by `dna emit --target agent-framework` (copilot case). INSTRUCTIONS is
the DNA-composed prompt (Soul + guardrails + instruction), carried byte-equal —
edit the agent in DNA and re-emit, never hand-edit the prompt here.

The per-run factory (`build_agent` / `build_workflow`) is what the serving layer
calls, mirroring the foundry reference's Foundry-backed `as_agent(...)` factories.
Tool bodies + any per-app retrieval (AzureAISearchContextProvider) are wired at
the consumer.
"""
import contextvars

from agent_framework import Agent
from agent_framework.foundry import FoundryChatClient
from azure.identity import DefaultAzureCredential
from agent_framework import MCPStreamableHTTPTool
from agent_framework import (
    AgentExecutorResponse,
    Executor,
    Workflow,
    WorkflowBuilder,
    WorkflowContext,
    handler,
    response_handler,
)
INSTRUCTIONS = "Remember and recall the user's notes. Confirm before writing.\n\nYou are the Helpdesk Concierge, an internal engineering support assistant. You help developers triage and resolve engineering questions."

#: Request-scoped tenant carrier. The serving layer sets it from inbound request
#: headers; the MCP `header_provider` reads it to stamp the outbound DNA tenant
#: headers on every federated MCP call (the inbound->outbound tenant bridge — NOT
#: a propagate_tenant freebie). DNA tenancy = `tenant` (Entra tid) + `workspace`
#: (→ scope `tenant-<workspace_id>`) + `personal:<oid>` (oid server-derived) — no
#: license, no namespace.
_CURRENT_TENANT: contextvars.ContextVar[dict] = contextvars.ContextVar(
    "dna_tenant", default={}
)

#: Inbound AG-UI request headers → the per-run tenant carrier. DNA-native only,
#: server-trusted (these are set service-to-service, never by the browser).
_TENANT_HEADERS = {
    "tenant": "X-DNA-Tenant",
    "workspace": "X-DNA-Workspace",
    "oid": "X-Tenant-OID",
}


def tenant_from_headers(headers) -> dict:
    """Derive the per-run DNA tenant/oid from the inbound request headers."""
    return {key: headers.get(header) for key, header in _TENANT_HEADERS.items()}


def set_request_tenant(tenant: dict):
    """Set the request-scoped tenant (called by the serving middleware); returns
    the ContextVar reset token the middleware restores after the run."""
    return _CURRENT_TENANT.set(tenant)


def reset_request_tenant(token) -> None:
    """Restore the tenant carrier after the request (paired with set_request_tenant)."""
    _CURRENT_TENANT.reset(token)


def _tenant_header_provider(_existing: dict) -> dict:
    """Stamp the request tenant onto every federated MCP call. Reads the
    request-scoped ContextVar the serving layer set from inbound headers — the
    outbound half of DNA tenant propagation."""
    tenant = _CURRENT_TENANT.get()
    headers: dict = {}
    if tenant.get("tenant"):
        headers["X-DNA-Tenant"] = tenant["tenant"]
    if tenant.get("workspace"):
        headers["X-DNA-Workspace"] = tenant["workspace"]
    if tenant.get("oid"):
        headers["X-Tenant-OID"] = tenant["oid"]
    return headers

def _mcp_tools() -> list[MCPStreamableHTTPTool]:
    """The DNA MCP server(s) this copilot mounts over Streamable HTTP. Tool bodies
    live on the remote MCP server, not in this scaffold. `allowed_tools` bounds
    what the model may call; `approval_mode` carries the tool-level HITL —
    `always_require_approval` write tools pause for the AG-UI approval card before
    they run, reads never do (a workflow copilot gates writes at the workflow
    level instead, so it mounts with `never_require`)."""
    return [
        MCPStreamableHTTPTool(
            name="mcp_dna-mcp",
            url="https://mcp.dna.example/agui",
            allowed_tools=["forget", "recall", "remember"],
            approval_mode="never_require",
            header_provider=_tenant_header_provider,
        ),
    ]

#: Per-step instructions are per-app bodies (a de-para loss): each workflow step
#: runs its own Foundry agent. The mounted agent's composed prompt is carried as
#: INSTRUCTIONS (byte-equal) and used by the first step; the rest are stubs.
_STEP_INSTRUCTIONS = "TODO: per-step instructions (see EmitResult.losses)."


def _client() -> FoundryChatClient:
    return FoundryChatClient(
        model="azure/gpt-4o",
        credential=DefaultAzureCredential(),
    )


def build_triage_agent() -> Agent:
    """Workflow step `triage` — a Foundry-backed ChatAgent. Its `name` becomes the
    workflow executor id the AG-UI adapter surfaces as the UI step name."""
    return _client().as_agent(
        name="triage",
        instructions=INSTRUCTIONS,
        tools=_mcp_tools(),
    )


def build_retrieve_agent() -> Agent:
    """Workflow step `retrieve` — a Foundry-backed ChatAgent. Its `name` becomes the
    workflow executor id the AG-UI adapter surfaces as the UI step name."""
    return _client().as_agent(
        name="retrieve",
        instructions=_STEP_INSTRUCTIONS,
    )


def build_resolve_agent() -> Agent:
    """Workflow step `resolve` — a Foundry-backed ChatAgent. Its `name` becomes the
    workflow executor id the AG-UI adapter surfaces as the UI step name."""
    return _client().as_agent(
        name="resolve",
        instructions=_STEP_INSTRUCTIONS,
    )


class EscalationExecutor(Executor):
    """Workflow-level HITL gate (design §6.1): a `request_info` node that pauses the
    workflow for human approval and acts only in the `@response_handler` after
    approval — chosen over a tool-level gate because the AG-UI workflow adapter
    double-emits TOOL_CALL_START for an approval-gated tool call. Mirrors the
    foundry reference's escalation node; the decision arrives over the
    `{interrupts: [{id, value}]}` resume shape. The gated effect is a per-app body."""

    def __init__(self) -> None:
        super().__init__(id="escalate")

    @handler
    async def on_step(
        self, response: AgentExecutorResponse, ctx: WorkflowContext[str, str]
    ) -> None:
        text = (response.agent_response.text or "").strip()
        # Pause for human approval before the gated action runs.
        await ctx.request_info(request_data=text, response_type=bool)

    @response_handler
    async def on_decision(
        self, request: str, approved: bool, ctx: WorkflowContext[str, str]
    ) -> None:
        # The gated effect (e.g. the DNA write) runs only after approval — wire it here.
        await ctx.yield_output("Approved." if approved else "No action taken.")


def build_workflow() -> Workflow:
    """Per-request factory: a `WorkflowBuilder` chain of the declared steps +
    the human-approval escalation node. Mirrors the foundry reference's
    `build_helpdesk_workflow`."""
    triage = build_triage_agent()
    retrieve = build_retrieve_agent()
    resolve = build_resolve_agent()
    escalate = EscalationExecutor()
    return (
        WorkflowBuilder(
            name="MemoryAgent",
            start_executor=triage,
        )
        .add_chain([triage, retrieve, resolve, escalate])
        .build()
    )
