"""DNA-emitted Agno copilot agent: memory-agent.

Generated by `dna emit --target agno` (copilot case). INSTRUCTIONS is the
DNA-composed prompt (Soul + guardrails + instruction), carried byte-equal — edit
the agent in DNA and re-emit, never hand-edit the prompt here.

`build_agent` is the per-run factory (cheap + network-free — mirrors the
Agno KB reference agent factory): the serving layer calls it with the run's
session_state so tenant/knowledge stay fresh without a restart.
"""
from __future__ import annotations

import os

from agno.agent import Agent
from agno.db.postgres import PostgresDb
from agno.knowledge.embedder.openai import OpenAIEmbedder
from agno.knowledge.knowledge import Knowledge
from agno.models.openai import OpenAILike
from agno.vectordb.pgvector import PgVector, SearchType
from agno.tools.mcp import MCPTools
INSTRUCTIONS = "Remember and recall the user's notes. Confirm before writing.\n\nYou are the Helpdesk Concierge, an internal engineering support assistant. You help developers triage and resolve engineering questions."


def _mcp_tools() -> list[MCPTools]:
    """The DNA MCP server(s) this copilot mounts over Streamable HTTP. The
    toolkit is CONSTRUCTED but NOT connected here — connecting is async and
    happens inside the AG-UI run loop. Tool bodies live on the remote MCP
    server, not in this scaffold.

    HITL (Spike 0A: gate-remote-directly): the DNA write tools are gated DIRECTLY
    on the remote MCP tool via `external_execution_required_tools` — no local
    wrapper. Agno pauses the run when the model calls a gated tool
    (`RunStatus.paused`, the tool in `tools_awaiting_external_execution`); the
    AG-UI approval card answers and Agno's router resumes it (`acontinue_run`)."""
    return [
        MCPTools(
            url="https://mcp.dna.example/agui",
            transport="streamable-http",
            external_execution_required_tools=["forget", "remember"],
        ),
    ]

def _knowledge() -> Knowledge:
    """The RAG store this copilot reads (`Copilot.knowledge`: knowledge-base).
    DNA declares a pgvector store (`knowledge.store`), so this binds a REAL Agno
    `Knowledge(vector_db=PgVector(...))` over Postgres — the DSN comes from the
    `primary-pg` infra ref via its env var (f-copilot-infra-binding wires it),
    NEVER a hardcoded literal. The corpus CONTENT is loaded per-app (call
    `_knowledge().add_content(...)` at wire-up)."""
    return Knowledge(
        vector_db=PgVector(
            table_name="knowledge_base",
            db_url=os.environ["DNA_PRIMARY_PG_URL"],
            search_type=SearchType.hybrid,
            embedder=OpenAIEmbedder(id="text-embedding-3-small", dimensions=1536),
        ),
    )

def build_agent(session_state: dict | None = None) -> Agent:
    """Build the Agno Agent for one run. No network is touched at build time — the
    model is constructed lazily. `db` binds Agno's `PostgresDb` to the `primary-pg`
    infra ref (DSN read from its env var — f-copilot-infra-binding wires it), so
    thread/run state + cross-session user memories survive restarts and HITL resume
    works across processes."""
    knowledge = _knowledge()
    return Agent(
        name="memory-agent",
        model=OpenAILike(id="azure/gpt-4o"),
        instructions=INSTRUCTIONS,
        tools=_mcp_tools(),
        knowledge=knowledge,
        search_knowledge=knowledge is not None,
        db=PostgresDb(db_url=os.environ["DNA_PRIMARY_PG_URL"]),
        enable_user_memories=True,
        session_state=session_state or {},
        add_session_state_to_context=True,
        markdown=True,
    )
