#!/usr/bin/env python3
"""Prose-coverage guard for the DNA docs (s-docs-coverage-guard). Pure stdlib.

The autogenerated Reference (docs/reference/**) can never drift — the drift
guard in docs.yml regenerates it from source and diffs. But the PROSE can:
search/memory shipped with zero concept/guide pages and nobody noticed until
a human looked. This guard closes that hole the same way: the sources of
truth are machine-readable, so prose COVERAGE is checkable.

What it enumerates (from source, never from the docs):
  * top-level ``dna`` CLI groups — introspected from the live Click tree
    (``dna_cli.main``), the same mechanism as ``scripts/gen_cli_docs.py``;
  * registered Kinds — introspected from ``Kernel.auto()``, the same
    mechanism as ``scripts/gen_kinds_docs.py``.

What counts as PROSE: ``docs/concepts/**``, ``docs/guides/**``,
``docs/getting-started/**`` — plus ``README.md``, which is deliberately
counted as valid prose (it is hand-written narrative and often the first
page a user reads). ``docs/reference/**`` NEVER counts: it is generated
from the same source being checked, so it would satisfy the guard
tautologically.

What counts as a MENTION (deliberately narrow — precision over recall):
  * a CLI group is covered only by an invocation-shaped mention,
    ``dna <group>`` (case-insensitive). Bare words like "search" or
    "memory" occur in ordinary prose constantly; counting them would have
    hidden exactly the search/memory gap that motivated this guard.
  * a Kind is covered by its exact CamelCase name as a whole word,
    case-SENSITIVELY, plural tolerated ("Stories" does not match — but
    "Epics"/"Features" do), or by its globally-unique alias
    (case-insensitive). Case-sensitivity matters for the same reason:
    "plan", "comment", "setting", "hook" are common English words.

Allowlist is EXPLICIT and versioned here, one justification string per
item, brand_guard style. Shrink-only by convention: entries are removed as
prose lands, never grown to paper over a new gap (a NEW public surface must
ship with prose or a justified entry reviewed on the PR). If an allowlisted
item becomes covered by prose, the guard prints a stale-entry NOTE asking
for its removal (a nudge, not a failure — so a sister docs PR can merge
first and the removal follow in its wake).

Usage:
    python3 scripts/docs_coverage_guard.py               # run the guard (exit 1 on gap)
    python3 scripts/docs_coverage_guard.py --self-test   # planted-gap self-tests
    python3 scripts/docs_coverage_guard.py --all         # report-only: ignore the allowlist

CI runs ``--self-test`` first, then the real guard (docs-build job in
.github/workflows/docs.yml, after the reference drift guard).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

# Prose quadrants (Diátaxis: concepts/guides/getting-started). README.md is
# counted as valid prose — see the module docstring for the rationale.
PROSE_DIRS = ("docs/concepts", "docs/guides", "docs/getting-started")
PROSE_FILES = ("README.md",)

# --- allowlist: item key -> justification ------------------------------------
# Keys are "cli:<group>" or "kind:<KindName>". EVERY entry needs an honest,
# reviewable justification. Shrink-only by convention.

_SISTER = (
    "being documented in s-docs-search-memory-prose — REMOVE when it merges"
)
_CLI_GAP = (
    "pre-existing prose gap, surfaced by this guard's first run "
    "(s-docs-coverage-guard finding) — public CLI group that needs its own "
    "prose story; REMOVE when that prose lands"
)
_SDLC_MACHINERY = (
    "SDLC dogfooding machinery (record plane) — reached via `dna sdlc`; the "
    "SDLC guide covers the core arc (Roadmap/Epic/Feature/Story/Issue/Task/"
    "Spec) and this long-tail Kind needs no standalone public prose"
)
_KIND_GAP = (
    "public composition-plane Kind with no prose yet — pre-existing gap, "
    "surfaced by this guard's first run (s-docs-coverage-guard finding); "
    "REMOVE when its prose lands"
)

ALLOWLIST: dict[str, str] = {
    # -- TEMPORARY: sister story in flight (search/memory prose, #13-#16) ----
    # -- pre-existing CLI prose gaps (findings, tracked for follow-up) -------
    "cli:doc": _CLI_GAP,      # document CRUD (list/show/create/edit/delete)
    "cli:docs": _CLI_GAP,     # in-product Doc corpus browser
    "cli:kind": _CLI_GAP,     # list + inspect registered Kinds
    "cli:research": _CLI_GAP, # Research synthesis documents
    "cli:scope": _CLI_GAP,    # list + inspect scopes
    "cli:source": _CLI_GAP,   # source-level ops (replicas, introspection)
    # -- SDLC dogfooding machinery (record plane, long tail) -----------------
    "kind:ADR": _SDLC_MACHINERY,
    "kind:AgentSession": _SDLC_MACHINERY,
    "kind:ArchiveProposal": _SDLC_MACHINERY,
    "kind:AuditLog": _SDLC_MACHINERY,
    "kind:Bug": _SDLC_MACHINERY,
    "kind:Changelog": _SDLC_MACHINERY,
    "kind:CognitivePolicy": _SDLC_MACHINERY,
    "kind:Epic": _SDLC_MACHINERY,
    "kind:Forecast": _SDLC_MACHINERY,
    "kind:Initiative": _SDLC_MACHINERY,
    "kind:Insight": _SDLC_MACHINERY,
    "kind:Kaizen": _SDLC_MACHINERY,
    "kind:Narrative": _SDLC_MACHINERY,
    "kind:PatternInsight": _SDLC_MACHINERY,
    "kind:Plan": _SDLC_MACHINERY,
    "kind:Postmortem": _SDLC_MACHINERY,
    "kind:PreMortem": _SDLC_MACHINERY,
    "kind:PromptTemplate": _SDLC_MACHINERY,
    "kind:Retrospective": _SDLC_MACHINERY,
    "kind:RiskRegister": _SDLC_MACHINERY,
    "kind:Roadmap": _SDLC_MACHINERY,
    "kind:SavedView": _SDLC_MACHINERY,
    "kind:Spike": _SDLC_MACHINERY,
    "kind:StatusReport": _SDLC_MACHINERY,
    "kind:SynthesisRun": _SDLC_MACHINERY,
    "kind:SynthesizerState": _SDLC_MACHINERY,
    "kind:WorkflowEvent": _SDLC_MACHINERY,
    # -- composition-plane Kinds without prose (findings, follow-up) ---------
    "kind:Canvas": _KIND_GAP,
    "kind:Comment": _KIND_GAP,
    "kind:EvidencePolicy": _KIND_GAP,
    "kind:Hook": _KIND_GAP,
    "kind:Lesson": _KIND_GAP,
    "kind:MCPFederation": _KIND_GAP,
    "kind:Recognizer": _KIND_GAP,
    "kind:SafetyPolicy": _KIND_GAP,
    "kind:Setting": _KIND_GAP,
    "kind:TestGuide": _KIND_GAP,
    "kind:Theme": _KIND_GAP,
    "kind:UserProfile": _KIND_GAP,
    "kind:UserRoleAssignment": _KIND_GAP,
}


# --- item model ---------------------------------------------------------------
# An item is (key, label, patterns, fix_hint): covered iff ANY pattern matches
# ANY prose file. Patterns are compiled once; matching is pure text scan.


def _cli_item(group: str) -> tuple[str, str, list[re.Pattern[str]], str]:
    pat = re.compile(rf"\bdna\s+{re.escape(group)}\b", re.IGNORECASE)
    return (
        f"cli:{group}",
        f"CLI group `dna {group}`",
        [pat],
        f"mention it as `dna {group}` (an invocation, not the bare word)",
    )


def _kind_item(name: str, alias: str) -> tuple[str, str, list[re.Pattern[str]], str]:
    pats = [re.compile(rf"\b{re.escape(name)}(e?s)?\b")]  # case-SENSITIVE + plural
    if alias:
        pats.append(re.compile(rf"\b{re.escape(alias)}\b", re.IGNORECASE))
    return (
        f"kind:{name}",
        f"Kind `{name}` (alias `{alias}`)",
        pats,
        f"mention `{name}` (exact case) or its alias `{alias}`",
    )


# --- enumeration (same mechanisms as the reference generators) ----------------


def enumerate_cli_groups() -> list[str]:
    """Top-level `dna` command groups, from the live Click tree."""
    from dna_cli import main as cli_main

    return sorted(cli_main.commands)


def enumerate_kinds() -> list[tuple[str, str]]:
    """(kind, alias) for every Kind registered by ``Kernel.auto()``."""
    from dna.kernel import Kernel

    def get(port: object, attr: str) -> str:
        value = getattr(port, attr, None)
        return str(value() if callable(value) else value or "")

    kernel = Kernel.auto()
    pairs = {
        (get(p, "kind"), get(p, "alias"))
        for p in kernel.kind_ports()
        if get(p, "kind")
    }
    return sorted(pairs)


def load_prose(root: Path) -> dict[str, str]:
    """Relative path -> text for every prose page. reference/** never enters."""
    texts: dict[str, str] = {}
    for rel_dir in PROSE_DIRS:
        base = root / rel_dir
        for path in sorted(base.rglob("*.md")):
            texts[str(path.relative_to(root))] = path.read_text(encoding="utf-8")
    for rel in PROSE_FILES:
        path = root / rel
        if path.exists():
            texts[rel] = path.read_text(encoding="utf-8")
    return texts


# --- the check ----------------------------------------------------------------


def check(
    items: list[tuple[str, str, list[re.Pattern[str]], str]],
    texts: dict[str, str],
    allowlist: dict[str, str],
) -> tuple[list[tuple[str, str, str]], list[tuple[str, str]]]:
    """Return (missing, stale_allowlist).

    missing: (key, label, fix_hint) for uncovered, un-allowlisted items.
    stale_allowlist: (key, justification) for allowlisted items that ARE
    covered by prose — their entry should be removed (shrink-only ratchet).
    """
    missing: list[tuple[str, str, str]] = []
    stale: list[tuple[str, str]] = []
    for key, label, patterns, hint in items:
        covered = any(p.search(t) for p in patterns for t in texts.values())
        if covered and key in allowlist:
            stale.append((key, allowlist[key]))
        elif not covered and key not in allowlist:
            missing.append((key, label, hint))
    return missing, stale


def _report(
    missing: list[tuple[str, str, str]],
    stale: list[tuple[str, str]],
    n_items: int,
    n_pages: int,
) -> int:
    for key, justification in stale:
        print(
            f"NOTE: allowlist entry '{key}' is now covered by prose — remove it "
            f"from ALLOWLIST in scripts/docs_coverage_guard.py "
            f"(was: {justification})"
        )
    if missing:
        print(
            f"docs_coverage_guard: {len(missing)} public item(s) have NO prose "
            f"coverage (checked {n_items} items against {n_pages} prose pages):",
            file=sys.stderr,
        )
        for key, label, hint in missing:
            print(f"\n  {key} — {label}", file=sys.stderr)
            print(f"      fix: {hint}", file=sys.stderr)
        print(
            "\nWhere: add prose to docs/concepts/**, docs/guides/** or "
            "docs/getting-started/** (README.md also counts). The autogenerated "
            "docs/reference/** does NOT count — this guard is about hand-written "
            "prose. If an item is genuinely internal, add it to ALLOWLIST in "
            "scripts/docs_coverage_guard.py with an honest justification "
            "(allowlist is shrink-only by convention).",
            file=sys.stderr,
        )
        return 1
    print(
        f"docs_coverage_guard: clean — {n_items} public items all covered by "
        f"prose or justified in the allowlist ({n_pages} prose pages scanned)"
    )
    return 0


# --- self-test ------------------------------------------------------------------
# Pure stdlib, no dna imports: plants fake items against fake prose and proves
# every behaviour — gap fails, allowlist admits, mention passes, imprecise
# mentions (bare word / wrong case) do NOT count, stale entries are noted.


def self_test() -> int:
    failures: list[str] = []
    fake_cli = _cli_item("frobnicate")
    fake_kind = _kind_item("Zorblat", "zt-zorblat")
    items = [fake_cli, fake_kind]

    # 1. no prose at all -> both items missing
    missing, _ = check(items, {"docs/guides/x.md": "nothing here"}, {})
    if {m[0] for m in missing} != {"cli:frobnicate", "kind:Zorblat"}:
        failures.append(f"planted gap not caught: {missing}")

    # 2. allowlisted -> passes
    allow = {"cli:frobnicate": "test", "kind:Zorblat": "test"}
    missing, stale = check(items, {"docs/guides/x.md": "nothing"}, allow)
    if missing:
        failures.append(f"allowlisted items still flagged: {missing}")
    if stale:
        failures.append(f"uncovered allowlist entries wrongly marked stale: {stale}")

    # 3. mentioned in prose -> passes without allowlist
    prose = {"docs/concepts/x.md": "Run `dna frobnicate` to frob. A Zorblat is a Kind."}
    missing, _ = check(items, prose, {})
    if missing:
        failures.append(f"mentioned items flagged as missing: {missing}")

    # 4. precision: bare word (no `dna` prefix) and wrong-case kind do NOT count
    vague = {"docs/concepts/x.md": "frobnicate things; a zorblat too"}
    missing, _ = check(items, vague, {})
    if {m[0] for m in missing} != {"cli:frobnicate", "kind:Zorblat"}:
        failures.append(f"imprecise mention wrongly counted as coverage: {missing}")

    # 4b. plural + alias forms DO count
    forms = {"docs/guides/x.md": "dna frobnicate runs; Zorblats (aka ZT-ZORBLAT) exist"}
    missing, _ = check(items, forms, {})
    if missing:
        failures.append(f"plural/alias mention not recognised: {missing}")

    # 5. covered + allowlisted -> stale-entry note, not a failure
    missing, stale = check(items, prose, allow)
    if missing:
        failures.append(f"covered allowlisted items flagged missing: {missing}")
    if {s[0] for s in stale} != {"cli:frobnicate", "kind:Zorblat"}:
        failures.append(f"stale allowlist entries not detected: {stale}")

    if failures:
        print("docs_coverage_guard SELF-TEST FAILED:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print(
        "docs_coverage_guard self-test OK (gap fails, allowlist admits, mention "
        "passes, imprecise mentions rejected, stale entries noted)"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true",
                        help="run the planted-gap self-test (no dna imports)")
    parser.add_argument("--all", action="store_true",
                        help="report-only: show every gap, ignoring the allowlist")
    parser.add_argument("--root", default=None,
                        help="repo root to scan (default: this script's repo)")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    root = Path(args.root) if args.root else _REPO_ROOT
    try:
        cli_groups = enumerate_cli_groups()
        kinds = enumerate_kinds()
    except ImportError as exc:
        print(
            f"docs_coverage_guard: cannot enumerate the source of truth ({exc}).\n"
            "Install the SDK + CLI first: pip install -e packages/sdk-py -e packages/cli",
            file=sys.stderr,
        )
        return 1

    items = [_cli_item(g) for g in cli_groups]
    items += [_kind_item(name, alias) for name, alias in kinds]
    texts = load_prose(root)
    allowlist = {} if args.all else ALLOWLIST

    missing, stale = check(items, texts, allowlist)
    return _report(missing, stale, len(items), len(texts))


if __name__ == "__main__":
    sys.exit(main())
