#!/usr/bin/env bash
# Regenerate EVERY derived artifact in this repo, from THIS checkout, in one
# command.
#
# ⚠️ Why this file exists. Two reasons, and the second is worse than the first.
#
# 1. On 06-07/08/2026 CI went red FOUR times in one day on stale generated
#    artifacts, each time fixed by "run the generator nobody remembered". Then
#    a fifth time, to the person who had just written that rule: they derived
#    the list with `ls scripts/{gen_,dump_}*.py`, called it "the five", and
#    shipped a stale `packages/client-ts/src/schema.ts` — generated by an npm
#    script in ANOTHER package, invisible to that glob. A list derived from an
#    incomplete heuristic carries the authority of derivation and the coverage
#    of enumeration. The fix is not a better glob; it is one honest list.
#
# 2. ⚠️⚠️ THE GENERATORS READ THE INSTALLED PACKAGE, NOT THIS CHECKOUT.
#    Measured 07/08/2026: in the shared checkout, `uv run` resolved `dna_cli`
#    from a sibling worktree and `dna` from a third one — because every agent
#    that runs `uv pip install -e .` in its own worktree REPOINTS the shared
#    venv. A regeneration run that way emits a MIX of three trees: it produced
#    a `docs/reference/cli/invalidation.md` for a command that does not exist
#    in this checkout at all.
#
#    That is not only a docs problem. The same resolution governs `uv run
#    pytest`: a suite can pass against code that is not the code under review,
#    and nothing says so. See the board issue on venv cross-contamination.
#
#    Hence PYTHONPATH below, pinned to this checkout and verified before any
#    generator runs. Never remove it "because uv already handles it".
#
# ⚠️ Adding a generator? Add it HERE. That is the whole contract.

set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"
export PYTHONPATH="$ROOT/packages/sdk-py:$ROOT/packages/cli${PYTHONPATH:+:$PYTHONPATH}"

echo "── Verifying we are about to read THIS checkout ─────────────────"
uv run --no-project python - <<'PY'
import pathlib, sys
import dna, dna_cli
raiz = pathlib.Path.cwd().resolve()
for nome, mod in (("dna", dna), ("dna_cli", dna_cli)):
    onde = pathlib.Path(mod.__file__).resolve()
    marca = "OK  " if raiz in onde.parents else "ERRO"
    print(f"  {marca} {nome}: {onde.parent}")
    if raiz not in onde.parents:
        sys.exit(
            f"\n{nome} resolve OUTSIDE this checkout. Regenerating now would "
            f"emit another tree's artifacts.\nFix PYTHONPATH (or the venv's "
            f"editable install) before running this script."
        )
PY

echo
echo "── Python generators ────────────────────────────────────────────"
uv run --no-project python scripts/dump_openapi.py         # docs/openapi.json
uv run --no-project python scripts/gen_data_model_docs.py  # docs/reference/data-model.md
uv run --no-project python scripts/gen_kinds_docs.py       # docs/reference/kinds/*.md
uv run --no-project python scripts/gen_cli_docs.py         # docs/reference/cli/*.md
uv run --no-project python scripts/gen_ports_docs.py       # docs/reference/ports/*.md

echo
echo "── TypeScript client (npm script — NOT a scripts/*.py file) ─────"
# ⚠️ The one the glob misses. It reads docs/openapi.json, so it MUST run after
# dump_openapi.py — the order is load-bearing, not cosmetic.
( cd packages/client-ts && { bun run gen || npm run gen; } )

echo
echo "── What changed ─────────────────────────────────────────────────"
git status --porcelain -- docs/ packages/client-ts/src/schema.ts || true
echo
echo "(nothing listed above = every derived artifact was already in sync)"
