"""s-parity-behavioral-harness — Composition-V2 behavioral golden fixtures.

Executor of the golden case set at ``tests/golden-fixtures/composition/``
(repo root): each case materializes a scope tree, resolves a target document,
and deep-compares against a frozen ``expected/*.json``. The thirteen cases
cover the whole resolution surface — chain walk, rule lookup, tenant overlay,
catalog splice, field-level merge, cycle guard, non-inheritable denylist,
layer policy, and provenance.

Python is the SEMANTIC REFERENCE: the frozen ``expected/*.json`` files are
generated by THIS executor —

    DNA_REGEN_GOLDEN_FIXTURES=1 uv run pytest tests/test_composition_golden.py -q

— and committed after review. A mismatch is either a regression or an
intentional semantic change that must be re-frozen and reviewed as such.

History: these fixtures were also executed by a TypeScript twin. The
TypeScript SDK was frozen (tag ``sdk-ts-final``); the frozen expectations were
always generated from Python, so they carry their full value alone.

Protocol per case: materialize ``tree`` as a real .dna-style filesystem tree
in tmp, build a bare Kernel over a FilesystemWritableSource (the writable
variant is used because it implements ``list_scopes`` — required by the
Catalog tier scan in case 10; reads are identical to FilesystemSource),
resolve ``target``, deep-compare::

    {"chain": compute_resolution_chain(scope, tenant),
     "resolved": resolve_document(...).serialize()}
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pytest
import yaml

from dna.adapters.filesystem.writable import FilesystemWritableSource
from dna.kernel import Kernel

_REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURE_ROOT = _REPO_ROOT / "tests" / "golden-fixtures" / "composition"
CASE_DIR = FIXTURE_ROOT / "cases"
EXPECTED_DIR = FIXTURE_ROOT / "expected"
CASES = sorted(CASE_DIR.glob("*.yaml"))
REGEN = os.environ.get("DNA_REGEN_GOLDEN_FIXTURES") == "1"


def _write_doc(directory: Path, doc: dict[str, Any], index: int) -> None:
    name = (doc.get("metadata") or {}).get("name") or f"doc-{index}"
    filename = f"{str(doc.get('kind', 'doc')).lower()}-{name}.yaml"
    (directory / filename).write_text(
        yaml.safe_dump(doc, sort_keys=False), encoding="utf-8",
    )


def _materialize(tree: dict[str, Any], base: Path) -> None:
    """Write the case's scope tree as a real filesystem source layout.

    - base docs      → <base>/<scope>/<kind>-<name>.yaml
    - tenant overlay → <base>/tenants/<t>/scopes/<scope>/<kind>-<name>.yaml

    A scope with an empty doc list still gets its directory (pins the
    "scope exists but is empty" semantics — e.g. case 13).
    """
    for scope, docs in (tree.get("scopes") or {}).items():
        scope_dir = base / scope
        scope_dir.mkdir(parents=True, exist_ok=True)
        for i, doc in enumerate(docs or []):
            _write_doc(scope_dir, doc, i)
    for tenant, scopes in (tree.get("tenants") or {}).items():
        for scope, docs in (scopes or {}).items():
            overlay_dir = base / "tenants" / tenant / "scopes" / scope
            overlay_dir.mkdir(parents=True, exist_ok=True)
            for i, doc in enumerate(docs or []):
                _write_doc(overlay_dir, doc, i)


def test_fixture_set_present() -> None:
    """The golden fixture dir must exist and hold the minimum case set."""
    assert CASE_DIR.is_dir(), f"missing shared fixture dir: {CASE_DIR}"
    assert len(CASES) >= 10, (
        f"golden harness requires >=10 cases, found {len(CASES)} in {CASE_DIR}"
    )


@pytest.mark.parametrize("case_path", CASES, ids=lambda p: p.stem)
def test_case_id_matches_stem(case_path: Path) -> None:
    case = yaml.safe_load(case_path.read_text(encoding="utf-8"))
    assert case.get("id") == case_path.stem, (
        f"{case_path.name}: id {case.get('id')!r} != file stem {case_path.stem!r}"
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("case_path", CASES, ids=lambda p: p.stem)
async def test_composition_golden_fixture(case_path: Path, tmp_path: Path) -> None:
    case = yaml.safe_load(case_path.read_text(encoding="utf-8"))
    _materialize(case.get("tree") or {}, tmp_path)

    kernel = Kernel()
    kernel.source(FilesystemWritableSource(tmp_path))

    target = case["target"]
    tenant = target.get("tenant") or None

    chain = await kernel._compute_resolution_chain(target["scope"], tenant)
    resolved = await kernel.resolve_document(
        target["scope"], target["kind"], target["name"], tenant=tenant,
    )
    # json round-trip → tuples become lists, guaranteed JSON-clean compare.
    actual = json.loads(json.dumps({
        "chain": chain,
        "resolved": resolved.serialize(),
    }))

    expected_path = EXPECTED_DIR / f"{case_path.stem}.json"
    if REGEN:
        EXPECTED_DIR.mkdir(parents=True, exist_ok=True)
        expected_path.write_text(
            json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8",
        )
    assert expected_path.exists(), (
        f"frozen expected missing for {case_path.stem} — generate with "
        f"DNA_REGEN_GOLDEN_FIXTURES=1 uv run pytest "
        f"tests/test_composition_golden.py -q (then review + commit)"
    )
    expected = json.loads(expected_path.read_text(encoding="utf-8"))
    assert actual == expected, (
        f"{case_path.stem}: resolution diverged from frozen expected "
        f"({expected_path.relative_to(_REPO_ROOT)})"
    )
