"""H5 enforcement — track KindBase adoption across all extensions.

Goal: every Kind eventually inherits from ``KindBase`` (the
default-providing base introduced in H5). Until the migration of all
40+ Kinds is complete, this test acts as a **transition gate**:

  - Maintains an explicit allow-list of pre-KindBase Kinds (the 31
    Kinds NOT yet migrated as of this writing).
  - **New Kinds added outside the allow-list MUST inherit from
    KindBase** — the test fails otherwise. This prevents the migration
    from regressing as the codebase grows.
  - Migrated Kinds get removed from the allow-list — the test fails if
    a Kind is in the allow-list but already inherits from KindBase
    (forces the list to stay accurate as migrations land).

Allow-list shrinkage is the migration progress metric. v1.0 ships
with 9/40 KindBase-based; subsequent PRs migrate the rest by removing
entries from ``_PRE_KINDBASE_ALLOWLIST`` here.
"""
from __future__ import annotations

from dna.kernel import Kernel
from dna.kernel.kind_base import KindBase


def _is_compliant(kp) -> bool:
    """A Kind is H5-compliant when it gets KindBase semantics through one
    of the two CANONICAL authoring paths:

      1. a hand-written class inheriting ``KindBase``;
      2. F3 (spec 2026-06-10-kinds-descriptor-f3): a ``DeclarativeKindPort``
         synthesized from a ``kinds/*.kind.yaml`` descriptor
         (``__declarative__ = True``) — it mirrors the KindBase defaults
         structurally and unions ``KindBase.VOLATILE_SPEC_FIELDS``, so it
         is not a "pre-KindBase" ad-hoc port. Pilot: Kaizen.

    Ad-hoc hand-written KindPort classes remain forbidden.
    """
    return isinstance(kp, KindBase) or getattr(kp, "__declarative__", False)


# Pre-KindBase Kinds awaiting migration. Each entry: (api_version, kind).
# Removing an entry signals "migrated"; adding an entry is FORBIDDEN
# (new Kinds must use KindBase from day one).
#
# Generated by running:
#   uv run python -c "from dna.kernel import Kernel; \
#     from dna.kernel.kind_base import KindBase; \
#     k = Kernel.auto(); \
#     pre = sorted([key for key, kp in k._kinds.items() if not isinstance(kp, KindBase)]); \
#     [print(f'    {key},') for key in pre]"
_PRE_KINDBASE_ALLOWLIST: set[tuple[str, str]] = set()
# v1.0 ships with 100% KindBase adoption. Adding entries here would
# regress the migration — don't unless a deliberate decision is made
# (e.g. an extension intentionally implements KindPort directly to
# avoid the inheritance cost). Document the rationale in the PR.


def _all_registered_kind_keys() -> set[tuple[str, str]]:
    """Return the (api_version, kind) tuples of every Kind currently
    registered by ``Kernel.auto()`` — i.e. the production set of Kinds
    a vanilla install boots with."""
    k = Kernel.auto()
    return set(k._kinds.keys())


def test_no_new_pre_kindbase_kinds():
    """Every registered Kind that does NOT inherit from KindBase
    MUST appear in the allow-list. This catches new Kinds being
    written without ``class XKind(KindBase):``."""
    k = Kernel.auto()
    pre_kindbase = {
        key for key, kp in k._kinds.items()
        if not _is_compliant(kp)
    }
    new_offenders = pre_kindbase - _PRE_KINDBASE_ALLOWLIST
    assert not new_offenders, (
        f"New Kinds registered without KindBase inheritance: {sorted(new_offenders)}.\n"
        f"Either:\n"
        f"  1. Make the Kind class inherit from dna.kernel.kind_base.KindBase, OR\n"
        f"  2. Add the (api_version, kind) tuple to _PRE_KINDBASE_ALLOWLIST in this file\n"
        f"     (only if migration is intentionally deferred — explain why in the PR).\n"
        f"See docs/KIND-AUTHORING.md for the canonical pattern."
    )


def test_allowlist_does_not_drift_stale():
    """Entries in the allow-list must reference Kinds that are
    actually registered AND not yet on KindBase. If a Kind has been
    migrated (now inherits KindBase), its entry must be removed from
    the allow-list — keeps the migration progress metric honest."""
    k = Kernel.auto()
    registered = set(k._kinds.keys())

    # 1. Allow-list shouldn't reference Kinds that don't exist anymore
    nonexistent = _PRE_KINDBASE_ALLOWLIST - registered
    assert not nonexistent, (
        f"Allow-list references Kinds that aren't registered: {sorted(nonexistent)}. "
        f"Probably renamed/removed — clean up _PRE_KINDBASE_ALLOWLIST."
    )

    # 2. Allow-list shouldn't reference Kinds that ARE on KindBase
    already_migrated = {
        key for key in _PRE_KINDBASE_ALLOWLIST
        if key in registered and _is_compliant(k._kinds[key])
    }
    assert not already_migrated, (
        f"Allow-list references Kinds that already inherit KindBase: "
        f"{sorted(already_migrated)}. Remove these entries — the "
        f"migration is done for them."
    )


def test_kindbase_adoption_progress():
    """Visibility test (always passes) — prints the adoption ratio
    so PR diffs make migration progress visible. Run with
    ``pytest -v -k adoption_progress`` to see it."""
    k = Kernel.auto()
    total = len(k._kinds)
    on_base = sum(1 for kp in k._kinds.values() if _is_compliant(kp))
    pct = (on_base * 100) // total if total else 0
    # Always passes — this is a visibility test, not a gate.
    print(f"\nKindBase adoption: {on_base}/{total} ({pct}%)")
    assert on_base == total, (
        f"Regression: KindBase adoption dropped from 100%. "
        f"{total - on_base} Kinds no longer inherit from KindBase. "
        f"See test_no_new_pre_kindbase_kinds for the offenders list."
    )
