"""Anti-drift guard: the committed parity-matrix page must match the generator.

``docs/reference/parity-matrix.md`` is generated by
``scripts/gen_parity_matrix.py`` from the parity fixtures. The docs CI
regenerates it on every build (so the *published* site never drifts), and the
committed copy is a reviewable convenience. This test keeps that committed copy
honest: it re-runs the generator and fails if the page on disk is stale, so a
fixture edit that isn't reflected in the page (or a hand-edit of the page) reds
the Python suite.
"""
from __future__ import annotations

import importlib.util
import pathlib

_ROOT = pathlib.Path(__file__).resolve().parents[3]
_SCRIPT = _ROOT / "scripts" / "gen_parity_matrix.py"
_PAGE = _ROOT / "docs" / "reference" / "parity-matrix.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_parity_matrix", _SCRIPT)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_parity_matrix_is_fresh() -> None:
    gen = _load_generator()
    expected = gen.generate()
    assert _PAGE.exists(), f"{_PAGE} missing — run `python scripts/gen_parity_matrix.py`"
    actual = _PAGE.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/reference/parity-matrix.md is STALE relative to the parity "
        "fixtures. Run `python scripts/gen_parity_matrix.py` and commit the "
        "result."
    )


def test_generator_is_deterministic() -> None:
    gen = _load_generator()
    assert gen.generate() == gen.generate()
