"""DNA-emitted LangGraph copilot agent: memory-agent.

Generated by `dna emit --target langgraph` (copilot case). INSTRUCTIONS is the
DNA-composed prompt (Soul + guardrails + instruction), carried byte-equal — edit
the agent in DNA and re-emit, never hand-edit the prompt here.

The graph factory (`build_agent` / `build_workflow`) is what the serving layer
calls: a `StateGraph` compiled to an AG-UI-native CoAgent (LangGraph is AG-UI
native). Tool bodies live on the remote DNA MCP server; per-node bodies are wired
at the consumer.
"""
import contextvars
from typing import Annotated, TypedDict

from langchain_core.messages import AnyMessage, SystemMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.prebuilt import ToolNode
from langgraph.types import interrupt
INSTRUCTIONS = "Remember and recall the user's notes. Confirm before writing.\n\nYou are the Helpdesk Concierge, an internal engineering support assistant. You help developers triage and resolve engineering questions."


class State(TypedDict):
    """The graph state — the LangGraph-native carrier. `messages` is the running
    transcript; `tenant` rides IN the state (DNA tenancy = tenant + workspace +
    oid), read by every node and stamped onto outbound MCP calls."""

    messages: Annotated[list[AnyMessage], add_messages]
    tenant: dict


#: Request-scoped tenant carrier. The serving layer sets it from inbound request
#: headers (and seeds it into the graph state); this ContextVar lets the MCP
#: client stamp the outbound DNA tenant headers on every federated call (the
#: inbound->outbound tenant bridge). DNA tenancy = `tenant` (Entra tid) +
#: `workspace` (→ scope `tenant-<workspace_id>`) + `personal:<oid>` (oid
#: server-derived) — no license, no namespace.
_CURRENT_TENANT: contextvars.ContextVar[dict] = contextvars.ContextVar(
    "dna_tenant", default={}
)

#: Inbound AG-UI request headers → the per-run tenant carrier. DNA-native only,
#: server-trusted (these are set service-to-service, never by the browser).
_TENANT_HEADERS = {
    "tenant": "X-DNA-Tenant",
    "workspace": "X-DNA-Workspace",
    "oid": "X-Tenant-OID",
}


def tenant_from_headers(headers) -> dict:
    """Derive the per-run DNA tenant/oid from the inbound request headers."""
    return {key: headers.get(header) for key, header in _TENANT_HEADERS.items()}


def set_request_tenant(tenant: dict):
    """Set the request-scoped tenant (called by the serving middleware); returns
    the ContextVar reset token the middleware restores after the run."""
    return _CURRENT_TENANT.set(tenant)


def reset_request_tenant(token) -> None:
    """Restore the tenant carrier after the request (paired with set_request_tenant)."""
    _CURRENT_TENANT.reset(token)


def _tenant_headers() -> dict:
    """Stamp the request tenant onto every federated MCP call. Reads the
    request-scoped ContextVar the serving layer set from inbound headers — the
    outbound half of DNA tenant propagation."""
    tenant = _CURRENT_TENANT.get()
    headers: dict = {}
    if tenant.get("tenant"):
        headers["X-DNA-Tenant"] = tenant["tenant"]
    if tenant.get("workspace"):
        headers["X-DNA-Workspace"] = tenant["workspace"]
    if tenant.get("oid"):
        headers["X-Tenant-OID"] = tenant["oid"]
    return headers


def _model():
    """The chat model for the graph's nodes. The DNA coordinate is carried verbatim;
    `init_chat_model` resolves it (provider prefixes: openai / anthropic /
    azure_openai / google_genai — a DNA `azure/…` coordinate needs `azure_openai:`)."""
    from langchain.chat_models import init_chat_model

    return init_chat_model('azure/gpt-4o')



def _mcp_client() -> MultiServerMCPClient:
    """The DNA MCP server(s) this copilot mounts over Streamable HTTP
    (langchain-mcp-adapters). Tool bodies live on the remote MCP server, not in
    this scaffold. The DNA tenant headers are stamped per-call from the
    request-scoped carrier — the outbound half of tenant propagation."""
    return MultiServerMCPClient(
        {
            'mcp_dna-mcp': {
                "url": 'https://mcp.dna.example/agui',
                "transport": "streamable_http",
                "headers": _tenant_headers(),
            },
        }
    )



async def _triage_node(state: State) -> dict:
    """Workflow step `triage` — a graph node in the chain. Runs the mounted agent's
    byte-equal INSTRUCTIONS + the DNA MCP tools — the per-step body is a per-app
    stub (see EmitResult.losses)."""
    tenant = state.get("tenant") or _CURRENT_TENANT.get()
    model = _model()
    model = model.bind_tools(await _mcp_client().get_tools())
    reply = await model.ainvoke([SystemMessage(INSTRUCTIONS), *state["messages"]])
    return {"messages": [reply], "tenant": tenant}



async def _retrieve_node(state: State) -> dict:
    """Workflow step `retrieve` — a graph node in the chain. The per-step body is a per-app stub
    (see EmitResult.losses)."""
    reply = await _model().ainvoke(state["messages"])
    return {"messages": [reply]}



async def _resolve_node(state: State) -> dict:
    """Workflow step `resolve` — a graph node in the chain. The per-step body is a per-app stub
    (see EmitResult.losses)."""
    reply = await _model().ainvoke(state["messages"])
    return {"messages": [reply]}



def _review_node(state: State) -> dict:
    """Workflow-level graph-enforced HITL: a dedicated `interrupt()` node appended to
    the chain (the LangGraph-native equivalent of MS-AF's `request_info` escalation
    node). CopilotKit's `useInterrupt` answers; the gated effect runs only after
    approval — wire it at the consumer."""
    summary = state["messages"][-1].content if state["messages"] else ""
    interrupt({"awaiting_approval": summary})
    return {"messages": []}


def build_workflow():
    """Per-request factory: the declared `workflow.chain` AS graph nodes. LangGraph is
    graph-native, so a multi-step chain is just `add_edge` from step to step + a
    `review` interrupt node for human approval — the cleanest workflow shape of the
    three runtime targets."""
    from langgraph.checkpoint.memory import MemorySaver

    graph = StateGraph(State)
    graph.add_node('triage', _triage_node)
    graph.add_node('retrieve', _retrieve_node)
    graph.add_node('resolve', _resolve_node)
    graph.add_node("review", _review_node)
    graph.add_edge(START, 'triage')
    graph.add_edge('triage', 'retrieve')
    graph.add_edge('retrieve', 'resolve')
    graph.add_edge('resolve', 'review')
    graph.add_edge('review', END)
    return graph.compile(checkpointer=MemorySaver())
