"""DNA-emitted LangGraph copilot agent: memory-agent.

Generated by `dna emit --target langgraph` (copilot case). INSTRUCTIONS is the
DNA-composed prompt (Soul + guardrails + instruction), carried byte-equal — edit
the agent in DNA and re-emit, never hand-edit the prompt here.

The graph factory (`build_agent` / `build_workflow`) is what the serving layer
calls: a `StateGraph` compiled to an AG-UI-native CoAgent (LangGraph is AG-UI
native). Tool bodies live on the remote DNA MCP server; per-node bodies are wired
at the consumer.
"""
import contextvars
import os
from typing import Annotated, TypedDict

from langchain_core.messages import AnyMessage, SystemMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.prebuilt import ToolNode
from langgraph.types import interrupt
from dna.emit.mcp_ui import memory_list_card_html
INSTRUCTIONS = "Remember and recall the user's notes. Confirm before writing.\n\nYou are the Helpdesk Concierge, an internal engineering support assistant. You help developers triage and resolve engineering questions."


class State(TypedDict):
    """The graph state — the LangGraph-native carrier. `messages` is the running
    transcript; `tenant` rides IN the state (DNA tenancy = tenant + workspace +
    oid), read by every node and stamped onto outbound MCP calls.

    `memory_timeline` + `memory_card_html` are the Phase-2 generative-UI channel:
    when a READ tool (recall) runs, its result is projected into these
    keys and streamed to the frontend via the AG-UI state snapshot — the DNA
    console's Memória tab reads `agent.state.memory_timeline` (structured items)
    and renders `agent.state.memory_card_html` (the DNA-branded card) as an
    `<iframe srcDoc>` (scannable, not stuffed into the chat)."""

    messages: Annotated[list[AnyMessage], add_messages]
    tenant: dict
    memory_timeline: list
    memory_card_html: str


#: Request-scoped tenant carrier. The serving layer sets it from inbound request
#: headers (and seeds it into the graph state); this ContextVar lets the MCP
#: client stamp the outbound DNA tenant headers on every federated call (the
#: inbound->outbound tenant bridge). DNA tenancy = `tenant` (Entra tid) +
#: `workspace` (→ scope `tenant-<workspace_id>`) + `personal:<oid>` (oid
#: server-derived) — no license, no namespace.
_CURRENT_TENANT: contextvars.ContextVar[dict] = contextvars.ContextVar(
    "dna_tenant", default={}
)

#: Inbound AG-UI request headers → the per-run tenant carrier. DNA-native only,
#: server-trusted (these are set service-to-service, never by the browser).
_TENANT_HEADERS = {
    "tenant": "X-DNA-Tenant",
    "workspace": "X-DNA-Workspace",
    "oid": "X-Tenant-OID",
}


def tenant_from_headers(headers) -> dict:
    """Derive the per-run DNA tenant/oid from the inbound request headers."""
    return {key: headers.get(header) for key, header in _TENANT_HEADERS.items()}


def set_request_tenant(tenant: dict):
    """Set the request-scoped tenant (called by the serving middleware); returns
    the ContextVar reset token the middleware restores after the run."""
    return _CURRENT_TENANT.set(tenant)


def reset_request_tenant(token) -> None:
    """Restore the tenant carrier after the request (paired with set_request_tenant)."""
    _CURRENT_TENANT.reset(token)


def _tenant_headers() -> dict:
    """Stamp the request tenant onto every federated MCP call. Reads the
    request-scoped ContextVar the serving layer set from inbound headers — the
    outbound half of DNA tenant propagation."""
    tenant = _CURRENT_TENANT.get()
    headers: dict = {}
    if tenant.get("tenant"):
        headers["X-DNA-Tenant"] = tenant["tenant"]
    if tenant.get("workspace"):
        headers["X-DNA-Workspace"] = tenant["workspace"]
    if tenant.get("oid"):
        headers["X-Tenant-OID"] = tenant["oid"]
    return headers


def _model():
    """The chat model for the graph's nodes. The DNA coordinate is carried verbatim;
    `init_chat_model` resolves it (provider prefixes: openai / anthropic /
    azure_openai / google_genai — a DNA `azure/…` coordinate needs `azure_openai:`)."""
    from langchain.chat_models import init_chat_model

    return init_chat_model('azure/gpt-4o')

def _mcp_client() -> MultiServerMCPClient:
    """The DNA MCP server(s) this copilot mounts over Streamable HTTP
    (langchain-mcp-adapters). Tool bodies live on the remote MCP server, not in
    this scaffold. The DNA tenant headers are stamped per-call from the
    request-scoped carrier — the outbound half of tenant propagation."""
    return MultiServerMCPClient(
        {
            'mcp_dna-mcp': {
                "url": 'https://mcp.dna.example/agui',
                "transport": "streamable_http",
                "headers": _tenant_headers(),
            },
        }
    )

async def _agent_node(state: State) -> dict:
    """The reasoning node: call the model with the byte-equal INSTRUCTIONS as the
    system prompt, binding the DNA MCP tools. Tenant rides IN the graph
    state (seeded from the request-scoped carrier)."""
    tenant = state.get("tenant") or _CURRENT_TENANT.get()
    model = _model()
    model = model.bind_tools(await _mcp_client().get_tools())
    reply = await model.ainvoke([SystemMessage(INSTRUCTIONS), *state["messages"]])
    return {"messages": [reply], "tenant": tenant}

async def _tool_node(state: State) -> dict:
    """Run the model's MCP tool calls (a LangGraph `ToolNode` over the tools the DNA
    MCP server exposes), then loop back to the agent node. After running, if a READ
    tool (recall) produced a result, project it into `memory_timeline`
    (structured items) + `memory_card_html` (the DNA-branded card) so the console's
    Memória canvas renders it (Phase-2 generative-UI over the AG-UI shared state)."""
    out = await ToolNode(await _mcp_client().get_tools()).ainvoke(state)
    mems = _read_tool_memories(out.get("messages", []))
    if mems is not None:
        out["memory_timeline"] = _memory_timeline(mems)
        out["memory_card_html"] = memory_list_card_html(mems)
    return out


#: Read tools whose result feeds the memory canvas — the "read-tool → canvas"
#: convention, driven off the copilot's mounted MCP read allowlist (and/or the
#: declared `memory-timeline` frontend panel). Writes are HITL-gated, never here.
_READ_TOOLS = {'recall'}


def _coerce_json(content):
    """Best-effort parse of an MCP ToolMessage's content into a Python object.
    langchain-mcp-adapters may hand back a JSON string, an already-parsed
    dict/list, or a list of MCP content blocks (`[{"type":"text","text":"…"}]`)."""
    import json

    if isinstance(content, (dict, list)) and not (
        isinstance(content, list) and content and isinstance(content[0], dict) and "text" in content[0]
    ):
        return content
    text = content
    if isinstance(content, list):
        # MCP text-content blocks → concatenated text
        text = "".join(
            b.get("text", "") for b in content if isinstance(b, dict)
        )
    if isinstance(text, str):
        try:
            return json.loads(text)
        except Exception:
            return None
    return None


def _read_tool_memories(new_messages) -> list | None:
    """If a read tool (recall) just ran, return its RAW memory list —
    the single parsed source both the timeline projection and the rendered card
    derive from. Returns None when no read-tool result is present (leaves the
    canvas unchanged)."""
    for m in new_messages:
        if getattr(m, "name", None) not in _READ_TOOLS:
            continue
        data = _coerce_json(getattr(m, "content", ""))
        mems = None
        if isinstance(data, dict):
            mems = data.get("memories") or data.get("results") or data.get("hits")
        elif isinstance(data, list):
            mems = data
        if isinstance(mems, list):
            return mems
    return None


def _memory_timeline(mems) -> list:
    """Project the raw memory list into the canvas item shape the frontend reads:
    `{id, text, when, tags, personal}` (mapped from `{name, summary, created_at,
    tags}`)."""
    items = []
    for i, mem in enumerate(mems):
        if not isinstance(mem, dict):
            continue
        items.append(
            {
                "id": str(mem.get("name") or mem.get("id") or i),
                "text": mem.get("summary") or mem.get("text") or mem.get("content") or "",
                "when": mem.get("created_at") or mem.get("when") or "",
                "tags": list(mem.get("tags") or []),
                "personal": bool(mem.get("personal") or mem.get("memory_scope") == "personal"),
            }
        )
    return items


#: The DNA write tools gated on human approval (`Tool.requires_confirmation`) — the
#: graph pauses on these via LangGraph `interrupt()`.
_CONFIRM_TOOLS = ['forget', 'remember']


def _review_node(state: State) -> dict:
    """Graph-enforced HITL: pause for human approval before a gated write tool runs.
    `interrupt()` suspends the graph (the LangGraph-native equivalent of Agno's
    `external_execution` / MS-AF's `request_info`); CopilotKit's `useInterrupt`
    renders the approval card and resumes the graph with the decision. The gated
    effect runs only after approval — wire the post-approval branch at the consumer."""
    last = state["messages"][-1]
    gated = [
        c["name"]
        for c in getattr(last, "tool_calls", None) or []
        if c["name"] in _CONFIRM_TOOLS
    ]
    interrupt({"awaiting_approval": gated})
    return {"messages": []}

def _route(state: State) -> str:
    """After the agent node: a gated tool call → `review` (HITL); any tool call →
    `tools`; no tool call → END."""
    calls = getattr(state["messages"][-1], "tool_calls", None) or []
    if not calls:
        return END
    if any(c["name"] in _CONFIRM_TOOLS for c in calls):
        return "review"
    return "tools"

def build_agent():
    """Build the AG-UI-native CoAgent graph for one run — a `StateGraph` compiled to
    a checkpointed graph the AG-UI adapter serves. LangGraph IS the graph, so the
    ReAct loop + the human-approval interrupt is expressed directly as nodes + edges. State is
    checkpointed to Postgres (`PostgresSaver`) + a `PostgresStore` for long-term memory
    (pgvector semantic search via `index=`); DSNs come from the infra refs via env
    vars (f-copilot-infra-binding wires them) — open the pool + `.setup()` at wire-up."""
    from langgraph.checkpoint.postgres import PostgresSaver
    from langgraph.store.postgres import PostgresStore

    graph = StateGraph(State)
    graph.add_node("agent", _agent_node)
    graph.add_node("tools", _tool_node)
    graph.add_node("review", _review_node)
    graph.add_edge(START, "agent")
    graph.add_conditional_edges("agent", _route)
    graph.add_edge("review", "tools")
    graph.add_edge("tools", "agent")
    return graph.compile(checkpointer=PostgresSaver.from_conn_string(os.environ["DNA_PRIMARY_PG_URL"]), store=PostgresStore.from_conn_string(os.environ["DNA_PRIMARY_PG_URL"], index={'dims': 1536, 'embed': 'openai:text-embedding-3-small'}))
