/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agents
         * @description List a scope's prompt-target agents, tenant-aware.
         */
        get: operations["agents_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{name}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Prompt
         * @description Compose one agent's system prompt LIVE (Soul + Guardrails +
         *     instruction), tenant-aware — the per-tenant overlay a static emit
         *     artifact cannot express. ``?explain=true`` adds per-section
         *     provenance (the ``dna explain`` map) to the same response.
         */
        get: operations["agent_prompt_v1_agents__name__prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board
         * @description A compact SDLC summary for a project's ``board_scope``: Story + Feature
         *     counts by status, totals, and the newest work items — the console's board
         *     card. Reuses the shared SDLC read impl (``list_stories_impl``).
         */
        get: operations["board_v1_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board Item
         * @description One board work-item's FULL doc — the console's item-detail drawer:
         *     title, status, description, acceptance_criteria, definition_of_done,
         *     timeline, feature/epic refs, and produces. Delegates to the CORE
         *     ``board_item_impl`` (zero logic here). 404s an unknown name (for this
         *     scope/tenant, or under an explicit ``kind`` hint).
         */
        get: operations["board_item_v1_board_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insights
         * @description List the tenant's IntelInsight docs (ranked), optionally filtered by
         *     ``state`` and/or originating source. The console's per-project view
         *     passes ``?source=<name>`` so a project shows only its own insights.
         */
        get: operations["insights_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insight Metrics
         * @description The feedback KPIs (precision + noise rate) over the tenant's insight
         *     stream, optionally for one ``source_ref``. Read-only; the arithmetic is
         *     the core ``feedback_metrics``.
         */
        get: operations["insight_metrics_v1_insights_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights/{name}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Insight State
         * @description Set an insight's feedback state (new|actioned|dismissed|snoozed) —
         *     the reader's disposition. Delegates the read-modify-write to the core.
         */
        patch: operations["set_insight_state_v1_insights__name__state_patch"];
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories
         * @description List the tenant's memory — base + the tenant's OWN overlay (per the #83
         *     isolation), never another tenant's.
         */
        get: operations["memories_v1_memories_get"];
        put?: never;
        /**
         * Remember Memory
         * @description Persist ONE memory (an ``Engram``) into the tenant's OWN overlay
         *     — the portal's ``remember`` / add affordance, tenant-scoped from the
         *     session (never base, never another tenant). Reuses the SAME CORE
         *     ``remember_impl`` the MCP ``remember`` tool delegates to (one core, three
         *     faces), so a memory added here is recalled identically by MCP/CLI. The
         *     deterministic ``_slug(summary)`` name it returns is the id the portal's
         *     ``DELETE /v1/memories/{name}`` targets to undo it.
         *
         *     PLAN-GATED (i-042): the same axes the MCP ``remember`` tool enforces —
         *     ``memory`` family, ``memory_mode='write'``, rate + daily cap — via the
         *     SAME shared core. 403 for a read-only tier, 429 over quota.
         */
        post: operations["remember_memory_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Memories
         * @description Import a MIF bundle into the CALLER'S OWN personal memory.
         *
         *     The remote face of ``dna memory import --personal``: it wraps the SAME
         *     core pipeline (``dna.memory.verbs.import_mif_docs`` →
         *     ``dna.memory.interchange.from_mif``), so MIF is stored verbatim as a
         *     passthrough ``Memory`` AND/OR projected to a recallable ``Engram`` with
         *     no format logic re-implemented anywhere else.
         *
         *     Body: ``{"bundle": <MIF>, "as": "both"|"passthrough"|"native",
         *     "dedupe": "id"|"content-hash"|"off"}``. ``bundle`` accepts the shapes the
         *     export side emits — a JSON-LD ``{"@graph": [...]}``, a bare list of
         *     Memory Units, or one Memory Unit.
         *
         *     **The write ALWAYS lands in the caller's personal partition**
         *     (``personal:<oid>``), never a workspace: personal memory follows the
         *     PERSON, not the workspace (decision B1 / ADR-personal-memory). The
         *     identity is derived SERVER-SIDE from the verified token's claims and is
         *     never accepted from the body or the query — a ``tenant``/``oid``/
         *     ``personal_id`` sent by a client is IGNORED here (INV-PERSONAL layer 1),
         *     and there is no fallback to a workspace or to ``DNA_PERSONAL_ID`` on an
         *     authenticated deployment. No resolvable identity ⇒ 403, nothing written.
         */
        post: operations["import_memories_v1_memories_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/personal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personal Memories
         * @description List the CALLER'S OWN personal memories — the READ face of the
         *     partition ``POST /v1/memories/import`` writes (i-046: the founder
         *     imported a memory and no portal surface could show it).
         *
         *     Same identity contract as the import, MIRRORED not re-derived: the
         *     ``personal:<oid>`` partition is resolved SERVER-SIDE from the verified
         *     token's claims (``--auth config``), and is never accepted from the
         *     query or body — a ``tenant``/``oid``/``personal_id`` a client sends is
         *     IGNORED (INV-PERSONAL layer 1). A SHARED bearer (``--auth token``) is
         *     not an identity, so that mode is always 403; ``--auth none`` (the
         *     single-user local deployment) may read ``DNA_PERSONAL_ID``, and there
         *     is no such fallback on an authenticated deployment. No resolvable
         *     identity ⇒ 403, nothing read.
         *
         *     The result unions the personal partition with the shared base scope
         *     (never any workspace's memory); each item is the ``list_memories``
         *     shape enriched with the per-ITEM ``personal`` flag (i-068), so a UI
         *     can chip the caller's own memories apart from the shared riders.
         *
         *     ``scope`` is accepted for back-compat but the read is PINNED to the
         *     server's base scope (i-069): every personal write lands there, so a
         *     forwarded workspace scope (``tenant-<ws>``) would target a partition
         *     nothing ever writes to and return an honest-looking EMPTY list while
         *     the caller's memories exist — personal reads and writes must resolve
         *     the SAME home. The response's ``scope`` reports the pinned home.
         */
        get: operations["personal_memories_v1_memories_personal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories Search
         * @description Recall the tenant's memory for ``q`` (hybrid/bi-temporal when the
         *     search extra is present, honest lexical otherwise), tenant-scoped.
         */
        get: operations["memories_search_v1_memories_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Delete ONE memory from the tenant's OWN overlay — the portal's
         *     ownership/delete. Never base, never another tenant (a 404 otherwise).
         *
         *     PLAN-GATED (i-042): a delete is a WRITE on the memory surface — the
         *     MCP twin (``forget``) passes ``memory_op='write'`` through the same
         *     guard, so this route does too.
         */
        delete: operations["delete_memory_v1_memories__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orgs
         * @description List the tenant's Organization docs (the console's top-level container).
         */
        get: operations["orgs_v1_orgs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects
         * @description List the tenant's Project docs (the multi-repo development-space
         *     containers the portfolio console aggregates).
         */
        get: operations["projects_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a Project inside ``workspace_id`` (decision A1 — the owning
         *     workspace is an explicit field on the Project). The caller must hold an
         *     ACTIVE WorkspaceMembership there, else **403**. The write scope and the
         *     project's ``board_scope`` are DERIVED from the workspace + slug and are
         *     deliberately not accepted from the caller. 400 on a blank
         *     workspace_id/name.
         */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Detail
         * @description One project's detail + its RESOLVED repos (``repo_refs`` → the Repo
         *     docs). 404 when the slug is unknown for this (scope, tenant).
         */
        get: operations["project_detail_v1_projects__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Members
         * @description List a project's members with their RESOLVED role (highest-role-wins
         *     across org + project grants; org-owner a superuser), tenant-scoped. When
         *     ``viewer`` is set, reports ``viewer.can_manage`` so the portal gates its
         *     write controls. 404 when the slug is unknown for this (scope, tenant).
         */
        get: operations["project_members_v1_projects__slug__members_get"];
        put?: never;
        /**
         * Set Project Member
         * @description Invite / set a user's PROJECT-scope role — the Membros panel's write.
         *     RBAC-guarded: ``actor`` (the acting user) must be Owner/Admin of the
         *     project/org, and only an Owner may grant Owner (403 otherwise). Upserts the
         *     same Membership doc, tenant-scoped to the caller's overlay. 404 for an
         *     unknown project; 422 for an unknown role.
         */
        post: operations["set_project_member_v1_projects__slug__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Project Member
         * @description Remove a user's PROJECT-scope grant — the Membros panel's remove.
         *     RBAC-guarded: ``actor`` must be Owner/Admin (removing an Owner needs
         *     Owner). Deletes only the project-scope Membership (an inherited org grant
         *     is untouched), tenant-scoped. 403 without permission, 404 when the user has
         *     no project grant here.
         */
        delete: operations["remove_project_member_v1_projects__slug__members__user__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repos
         * @description List the tenant's Repo docs (code repositories the portfolio references).
         */
        get: operations["repos_v1_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description List the tenant's watched IntelSource docs (the Direction stage).
         */
        get: operations["sources_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tid}/provision-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Tenant Owner
         * @description Ensure ``user`` is Owner of tenant ``tid`` when it has no Owner yet — the
         *     first-owner bootstrap. Idempotent (no-op if an Owner already exists).
         *     Returns the grants created (org-scope per referenced org + project-scope per
         *     orgless project). 400 on a missing tenant/user.
         */
        post: operations["provision_tenant_owner_v1_tenants__tid__provision_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tools
         * @description List a scope's Tool Kind surfaces (name + description), tenant-aware.
         */
        get: operations["tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Workspace Plan
         * @description Upsert the WorkspacePlan Kind assigning ``workspace_id`` → ``tier_id``
         *     (the billing→enforcement bridge). 400 on a missing workspace_id/tier_id.
         */
        put: operations["put_workspace_plan_v1_workspace_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspaces
         * @description List the workspaces the caller holds an ACTIVE membership in — the
         *     workspace switcher's data source. Membership is the enumeration key, never
         *     the ``tid``; a pending invite is not listed. Under config auth the caller
         *     is the verified token identity; under none/token a trusted portal passes
         *     ``actor_oid``/``actor_email``. Never returns a workspace the identity does
         *     not belong to (an unmatched identity gets an empty list, not an error).
         */
        get: operations["list_workspaces_v1_workspaces_get"];
        put?: never;
        /**
         * Create Workspace
         * @description Create a workspace and its first OWNER, in one call. The
         *     ``workspace_id`` is generated by the server (opaque + unguessable) — it is
         *     NOT accepted from the client, which is what makes takeover structurally
         *     impossible. ``slug`` defaults to a slugified ``name`` and is made unique.
         *     The caller's verified identity (oid + email; ``tid`` stored as provenance
         *     only) becomes the active owner. 400 on a blank name or a missing
         *     oid/email claim.
         */
        post: operations["create_workspace_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invites
         * @description Accept every pending invite the caller's VERIFIED sign-in claims — binds
         *     the durable ``oid`` + flips ``pending→active``. Under config auth the
         *     claims come from the verified token (the invitee is still pending, so this
         *     route is exempt from the membership bind); under none/token a trusted portal
         *     passes the verified Entra claims. The SECURITY gate (verified email only, no
         *     hijack of a bound grant) is enforced in the core impl — never here.
         */
        post: operations["accept_invites_v1_workspaces_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invite
         * @description Invite an identity (by email) into a workspace — a ``pending``
         *     WorkspaceMembership. RBAC: the actor must be Owner/Admin (only an Owner may
         *     invite an Owner). 403 without permission; 422 on an unknown role.
         */
        post: operations["create_invite_v1_workspaces__workspace_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Members
         * @description List a workspace's members (grants). RBAC: the actor must be
         *     Owner/Admin. Under config auth the actor is the verified token identity;
         *     under none/token pass ``actor_oid``/``actor_email`` (the trusted portal
         *     vouches the session). 403 without permission.
         */
        get: operations["workspace_members_v1_workspaces__workspace_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Workspace Member
         * @description Revoke (remove) a member's WorkspaceMembership — the Members panel remove
         *     (issue ``i-033``). RBAC: the actor must be Owner/Admin (403 else). The LAST
         *     remaining owner can NEVER be revoked (409, fail-closed). A target holding no
         *     grant here is 404 (clear no-op). Target named by ``target_email`` or
         *     ``target_oid`` (oid wins). Under ``--auth config`` the actor is the verified
         *     token identity; under none/token the trusted portal passes ``actor`` claims.
         */
        post: operations["revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/provision-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Workspace Owner
         * @description Reconcile the verified identity's membership in ``{workspace_id}`` — the
         *     every-sign-in idempotent no-op. Since decision **D5** this CREATES NOTHING:
         *     it requires an ACTIVE WorkspaceMembership and returns it (back-filling the
         *     Workspace identity doc only for an owner whose doc is missing). A caller
         *     holding no active membership here is **403** — including a stranger, so the
         *     anti-takeover answer is unchanged; workspaces are created by
         *     ``POST /v1/workspaces``, which mints its own id. 400 on a missing
         *     oid/email claim.
         */
        post: operations["provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitesResponse */
        AcceptInvitesResponse: {
            /**
             * Accepted
             * @default []
             */
            accepted: components["schemas"]["AcceptedInvite"][];
            /** Identity Email */
            identity_email?: string | null;
            /** Identity Oid */
            identity_oid?: string | null;
        };
        /** AcceptedInvite */
        AcceptedInvite: {
            /**
             * Activated
             * @default false
             */
            activated: boolean;
            /** Role */
            role?: string | null;
            /** Workspace Id */
            workspace_id: string;
        };
        /** AgentPromptResponse */
        AgentPromptResponse: {
            /** Agent */
            agent: string;
            /**
             * Attribution
             * @description How the section list was attributed (only with ?explain=true). 'declared': the agent renders through a kernel-owned template (named layout preset, Kind default, or the plain-instruction fallback) — the kernel authored both the template and the section aliases, so the section map is correct by construction. 'heuristic': the agent carries its OWN promptTemplate, and sections are detected by fail-soft string-matching Mustache blocks in that user-authored template — a section can be silently missing from, or over-reported in, 'sections' (the composed 'prompt' itself is still exact).
             */
            attribution?: ("declared" | "heuristic") | null;
            /** Model */
            model?: string | null;
            /** Prompt */
            prompt: string;
            /** Scope */
            scope: string;
            /**
             * Sections
             * @description Per-section provenance of the composed prompt (only with ?explain=true). One row per composed input the layout renders. The 'prompt' field is byte-identical to the non-explain compose — explain never re-renders. NOTE: when 'attribution' is 'heuristic' this list may silently omit (or over-report) sections; see 'attribution'.
             */
            sections?: components["schemas"]["PromptSectionProvenance"][] | null;
            /** Tenant */
            tenant?: string | null;
        };
        /** AgentSummary */
        AgentSummary: {
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** AgentsResponse */
        AgentsResponse: {
            /** Agents */
            agents: components["schemas"]["AgentSummary"][];
            /** Scope */
            scope: string;
        };
        /**
         * BoardCounts
         * @description Status→count maps (dynamic keys — a status label is data).
         */
        BoardCounts: {
            /**
             * Features
             * @default {}
             */
            features: {
                [key: string]: number;
            };
            /**
             * Stories
             * @default {}
             */
            stories: {
                [key: string]: number;
            };
        };
        /**
         * BoardItemResponse
         * @description One SDLC work-item's full doc. The nested AC/DoD/timeline/produces lists
         *     pass through VERBATIM (the drawer renders them raw), so they stay loosely
         *     typed; ``business_value`` may be a label or a number → ``Any``.
         */
        BoardItemResponse: {
            /**
             * Acceptance Criteria
             * @default []
             */
            acceptance_criteria: unknown[];
            /** Business Value */
            business_value?: unknown | null;
            /** Closed At */
            closed_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Definition Of Done
             * @default []
             */
            definition_of_done: unknown[];
            /** Description */
            description?: string | null;
            /** Epic */
            epic?: string | null;
            /** Feature */
            feature?: string | null;
            /** Kind */
            kind: string;
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /** Name */
            name: string;
            /** Priority */
            priority?: string | null;
            /**
             * Produces
             * @default []
             */
            produces: unknown[];
            /** Reporter */
            reporter?: string | null;
            /** Scope */
            scope: string;
            /** Status */
            status?: string | null;
            /** Tenant */
            tenant?: string | null;
            /**
             * Timeline
             * @default []
             */
            timeline: {
                [key: string]: unknown;
            }[];
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** BoardListItem */
        BoardListItem: {
            /** Created At */
            created_at?: string | null;
            /** Kind */
            kind: string;
            /** Name */
            name?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
        };
        /** BoardResponse */
        BoardResponse: {
            counts: components["schemas"]["BoardCounts"];
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["BoardListItem"][];
            /**
             * Recent
             * @default []
             */
            recent: components["schemas"]["BoardListItem"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
            totals: components["schemas"]["BoardTotals"];
        };
        /** BoardTotals */
        BoardTotals: {
            /**
             * Features
             * @default 0
             */
            features: number;
            /**
             * Stories
             * @default 0
             */
            stories: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** Body_accept_invites_v1_workspaces_accept_post */
        Body_accept_invites_v1_workspaces_accept_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_create_invite_v1_workspaces__workspace_id__invites_post */
        Body_create_invite_v1_workspaces__workspace_id__invites_post: {
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** Body_create_project_v1_projects_post */
        Body_create_project_v1_projects_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Workspace Id */
            workspace_id: string;
        };
        /** Body_create_workspace_v1_workspaces_post */
        Body_create_workspace_v1_workspaces_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /** Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post */
        Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post: {
            /** User */
            user: string;
        };
        /** Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post */
        Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_put_workspace_plan_v1_workspace_plan_put */
        Body_put_workspace_plan_v1_workspace_plan_put: {
            /**
             * Source
             * @default stripe
             */
            source: string;
            /** Status */
            status?: string | null;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
            /** Tier Id */
            tier_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** Body_remember_memory_v1_memories_post */
        Body_remember_memory_v1_memories_post: {
            /**
             * Affect
             * @default triumph
             */
            affect: string;
            /**
             * Area
             * @default general
             */
            area: string;
            /**
             * Owner
             * @default portal
             */
            owner: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags?: string[] | null;
        };
        /** Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post */
        Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post: {
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
            /** Target Email */
            target_email?: string | null;
            /** Target Oid */
            target_oid?: string | null;
        };
        /** Body_set_insight_state_v1_insights__name__state_patch */
        Body_set_insight_state_v1_insights__name__state_patch: {
            /** State */
            state: string;
        };
        /** Body_set_project_member_v1_projects__slug__members_post */
        Body_set_project_member_v1_projects__slug__members_post: {
            /** Actor */
            actor?: string | null;
            /** Role */
            role: string;
            /** User */
            user: string;
        };
        /**
         * CreateProjectResponse
         * @description ``POST /v1/projects`` — the created project. ``scope`` is DERIVED from the
         *     workspace (never caller-supplied).
         */
        CreateProjectResponse: {
            project: components["schemas"]["ProjectSummary"];
            /** Scope */
            scope: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /**
         * CreateWorkspaceResponse
         * @description ``POST /v1/workspaces`` — the created workspace. ``workspace_id`` is
         *     SERVER-MINTED; there is no request field for it.
         */
        CreateWorkspaceResponse: {
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            membership?: components["schemas"]["WorkspaceMemberSurface"] | null;
            /** Name */
            name: string;
            /**
             * Role
             * @default owner
             */
            role: string;
            /** Slug */
            slug: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** DeleteMemoryResponse */
        DeleteMemoryResponse: {
            /** Deleted */
            deleted: string;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * ImportFailure
         * @description One MIF doc that could not be written — reported, never swallowed.
         */
        ImportFailure: {
            /** Error */
            error: string;
            /** Id */
            id: string;
        };
        /**
         * ImportMemoriesResponse
         * @description The outcome of a MIF bundle import into the caller's PERSONAL partition.
         *
         *     The counts always reconcile with the bundle size
         *     (``imported + skipped + failed == received``), so a partial import is always
         *     VISIBLE — ``failed`` is a reported outcome, never a silent one.
         *     ``partition`` echoes only the SCHEME the write landed in (``personal``),
         *     never the concrete ``personal:<oid>`` value — echoing that back would leak
         *     the server-derived identity onto the wire.
         */
        ImportMemoriesResponse: {
            /**
             * As Mode
             * @default both
             */
            as_mode: string;
            /**
             * Dedupe
             * @default id
             */
            dedupe: string;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["ImportFailure"][];
            /** Failed */
            failed: number;
            /**
             * Ids
             * @default []
             */
            ids: string[];
            /** Imported */
            imported: number;
            /**
             * Partition
             * @default personal
             */
            partition: string;
            /** Received */
            received: number;
            /** Skipped */
            skipped: number;
        };
        /** InsightMetricsResponse */
        InsightMetricsResponse: {
            /**
             * Actioned
             * @default 0
             */
            actioned: number;
            /**
             * Counts
             * @default {}
             */
            counts: {
                [key: string]: number;
            };
            /**
             * Dismissed
             * @default 0
             */
            dismissed: number;
            /** Noise Rate */
            noise_rate?: number | null;
            /** Precision */
            precision?: number | null;
            /** Scope */
            scope: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Tenant */
            tenant?: string | null;
        };
        /** InsightStateResponse */
        InsightStateResponse: {
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /** State */
            state: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Insights */
            insights: components["schemas"]["IntelInsightSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** IntelInsightSummary */
        IntelInsightSummary: {
            /** Action */
            action?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Evidence Rating */
            evidence_rating?: string | null;
            /** Fact */
            fact?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Pirs
             * @default []
             */
            pirs: string[];
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Source Ref */
            source_ref?: string | null;
            /**
             * State
             * @default new
             */
            state: string;
            /** Title */
            title?: string | null;
            /** Why */
            why?: string | null;
        };
        /** IntelSourceSummary */
        IntelSourceSummary: {
            /**
             * Cadence
             * @default weekly
             */
            cadence: string;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /** Name */
            name?: string | null;
            /**
             * Pirs
             * @default []
             */
            pirs: string[];
            /**
             * Threshold
             * @default 0.6
             */
            threshold: number;
            /** Type */
            type?: string | null;
        };
        /** InviteInfo */
        InviteInfo: {
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Identity Email */
            identity_email?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** InviteResponse */
        InviteResponse: {
            invite: components["schemas"]["InviteInfo"];
            /** Workspace Id */
            workspace_id: string;
        };
        /** MemoriesResponse */
        MemoriesResponse: {
            /** Memories */
            memories: components["schemas"]["MemorySummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** MemorySummary */
        MemorySummary: {
            /** Area */
            area?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** OrgSummary */
        OrgSummary: {
            /** Display Name */
            display_name?: string | null;
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** OrgsResponse */
        OrgsResponse: {
            /** Orgs */
            orgs: components["schemas"]["OrgSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** OwnerGrant */
        OwnerGrant: {
            /** Role */
            role: string;
            /** Scope Ref */
            scope_ref: string;
            /** Scope Type */
            scope_type: string;
        };
        /**
         * PersonalMemoriesResponse
         * @description The caller's OWN personal memories (+ the shared base they union with).
         *
         *     Like :class:`ImportMemoriesResponse`, ``partition`` echoes only the SCHEME
         *     the read resolved (``personal``) — never the concrete ``personal:<oid>``
         *     value, which would leak the server-derived identity onto the wire. There is
         *     deliberately NO ``tenant`` field for the same reason.
         */
        PersonalMemoriesResponse: {
            /** Memories */
            memories: components["schemas"]["PersonalMemorySummary"][];
            /**
             * Partition
             * @default personal
             */
            partition: string;
            /** Scope */
            scope: string;
        };
        /**
         * PersonalMemorySummary
         * @description One memory as the PERSONAL list surface projects it — the core
         *     ``list_memories_impl`` item shape (i-068 enriched): the dashboard fields
         *     plus the per-ITEM ``personal`` flag. A personal read unions the caller's
         *     ``personal:<oid>`` partition with the shared base, so the flag varies per
         *     item (``True`` = the caller's own private memory; ``False`` = a shared
         *     base memory riding along).
         */
        PersonalMemorySummary: {
            /** Affect */
            affect?: string | null;
            /** Area */
            area?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Personal
             * @default false
             */
            personal: boolean;
            /** Summary */
            summary?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** ProjectDetailResponse */
        ProjectDetailResponse: {
            project: components["schemas"]["ProjectSummary"];
            /** Repos */
            repos: components["schemas"]["RepoSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** ProjectMemberSurface */
        ProjectMemberSurface: {
            /**
             * Is Org Owner
             * @default false
             */
            is_org_owner: boolean;
            /** Org Role */
            org_role?: string | null;
            /** Project Role */
            project_role?: string | null;
            /** Role */
            role: string;
            /** Role Display */
            role_display: string;
            /** Scope Note */
            scope_note?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** User */
            user: string;
            /**
             * You
             * @default false
             */
            you: boolean;
        };
        /** ProjectMemberViewer */
        ProjectMemberViewer: {
            /**
             * Can Manage
             * @default false
             */
            can_manage: boolean;
            /** Role */
            role?: string | null;
            /** User */
            user?: string | null;
        };
        /** ProjectMembersResponse */
        ProjectMembersResponse: {
            /** Members */
            members: components["schemas"]["ProjectMemberSurface"][];
            project: components["schemas"]["ProjectRef"];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
            viewer: components["schemas"]["ProjectMemberViewer"];
        };
        /** ProjectRef */
        ProjectRef: {
            /** Name */
            name?: string | null;
            /** Org Ref */
            org_ref?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Board Scope */
            board_scope?: string | null;
            /**
             * Intel Source Refs
             * @default []
             */
            intel_source_refs: string[];
            /** Name */
            name?: string | null;
            /** Org Ref */
            org_ref?: string | null;
            /**
             * Repo Refs
             * @default []
             */
            repo_refs: string[];
            /** Slug */
            slug?: string | null;
            /**
             * Visibility
             * @default private
             */
            visibility: string;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /** ProjectsResponse */
        ProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /**
         * PromptSectionProvenance
         * @description Provenance for ONE composed prompt section (``?explain=true``).
         *
         *     Mirrors the kernel's ``SectionProvenance.serialize()`` exactly — the same
         *     map ``dna explain`` prints. No field here is invented by the REST face.
         */
        PromptSectionProvenance: {
            /**
             * Hash
             * @description SHA-256 (full hex) of the resolved raw document composed into this section, or null when it could not be resolved.
             */
            hash?: string | null;
            /**
             * Is Inherited
             * @description True when 'origin' is a DIFFERENT scope than the requested one (the section is inherited from a parent/library scope).
             */
            is_inherited: boolean;
            /**
             * Kind
             * @description The contributing Kind (Agent/Soul/Skill/Guardrail/…).
             */
            kind: string;
            /**
             * Name
             * @description The contributing document name.
             */
            name: string;
            /**
             * Origin
             * @description Effective layer/scope the section resolved from — the scope that won ('(not found)' when resolution failed).
             */
            origin: string;
            /**
             * Overridden By Tenant
             * @description True when the tenant-resolved content of this section DIFFERS from the base resolution — a per-tenant overlay won. Always false when no tenant was requested.
             */
            overridden_by_tenant: boolean;
            /**
             * Section
             * @description Human label of the composed section, e.g. 'instruction', 'soul', 'skill:tdd', 'guardrail:polite'.
             */
            section: string;
            /**
             * Source
             * @description Canonical source artifact path, e.g. 'skills/tdd/SKILL.md' ('?' when the Kind declares no storage pattern).
             */
            source: string;
            /**
             * Version
             * @description metadata.version of the resolved document, when the author set one.
             */
            version?: string | null;
        };
        /** ProvisionTenantOwnerResponse */
        ProvisionTenantOwnerResponse: {
            /**
             * Grants
             * @default []
             */
            grants: components["schemas"]["OwnerGrant"][];
            /** Provisioned */
            provisioned: boolean;
            /** Reason */
            reason?: string | null;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
            /** User */
            user: string;
        };
        /** ProvisionWorkspaceOwnerResponse */
        ProvisionWorkspaceOwnerResponse: {
            membership?: components["schemas"]["WorkspaceMemberSurface"] | null;
            /** Provisioned */
            provisioned: boolean;
            /** Reason */
            reason?: string | null;
            /**
             * Workspace Created
             * @default false
             */
            workspace_created: boolean;
            /** Workspace Id */
            workspace_id: string;
        };
        /**
         * RecallResponse
         * @description The recall envelope is typed; each ``hit`` stays a loose dict — its shape
         *     varies with the search plane active (lexical vs. hybrid/semantic add
         *     ``retention``/``semantic``/``rank_*`` keys), so it is honestly dynamic.
         */
        RecallResponse: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Hits
             * @default []
             */
            hits: {
                [key: string]: unknown;
            }[];
            /** Query */
            query: string;
            /** Scope */
            scope: string;
            /**
             * Semantic
             * @default false
             */
            semantic: boolean;
        };
        /** RememberResponse */
        RememberResponse: {
            /** Indexed */
            indexed: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** RemoveMemberResponse */
        RemoveMemberResponse: {
            /** Removed */
            removed: string;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** RepoSummary */
        RepoSummary: {
            /** Default Branch */
            default_branch?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Provider
             * @default github
             */
            provider: string;
            /** Url */
            url?: string | null;
        };
        /** ReposResponse */
        ReposResponse: {
            /** Repos */
            repos: components["schemas"]["RepoSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** RevokeWorkspaceMemberResponse */
        RevokeWorkspaceMemberResponse: {
            /** Revoked */
            revoked: boolean;
            target: components["schemas"]["WorkspaceMemberSurface"];
            /** Workspace Id */
            workspace_id: string;
        };
        /** SetMemberInfo */
        SetMemberInfo: {
            /** Role */
            role: string;
            /** Scope Ref */
            scope_ref: string;
            /** Scope Type */
            scope_type: string;
            /** Status */
            status: string;
            /** User */
            user: string;
        };
        /** SetMemberResponse */
        SetMemberResponse: {
            member: components["schemas"]["SetMemberInfo"];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Scope */
            scope: string;
            /** Sources */
            sources: components["schemas"]["IntelSourceSummary"][];
            /** Tenant */
            tenant?: string | null;
        };
        /** ToolSummary */
        ToolSummary: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name?: string | null;
        };
        /** ToolsResponse */
        ToolsResponse: {
            /** Scope */
            scope: string;
            /** Tools */
            tools: components["schemas"]["ToolSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceMemberSummary */
        WorkspaceMemberSummary: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Identity Email */
            identity_email?: string | null;
            /** Invited At */
            invited_at?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * WorkspaceMemberSurface
         * @description The ``_ws_member_surface`` projection (a superset of
         *     :class:`WorkspaceMemberSummary` with the ``workspace_id`` + ``identity_oid``).
         */
        WorkspaceMemberSurface: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Identity Email */
            identity_email?: string | null;
            /** Identity Oid */
            identity_oid?: string | null;
            /** Invited At */
            invited_at?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /** WorkspaceMembersResponse */
        WorkspaceMembersResponse: {
            /** Members */
            members: components["schemas"]["WorkspaceMemberSummary"][];
            /** Workspace Id */
            workspace_id: string;
        };
        /** WorkspacePlanResponse */
        WorkspacePlanResponse: {
            /** Scope */
            scope: string;
            /** Status */
            status?: string | null;
            /** Tier Id */
            tier_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Slug */
            slug?: string | null;
            /** Workspace Id */
            workspace_id: string;
        };
        /**
         * WorkspacesResponse
         * @description ``GET /v1/workspaces`` — the caller's ACTIVE memberships, projected.
         */
        WorkspacesResponse: {
            /** Identity Email */
            identity_email?: string | null;
            /** Identity Oid */
            identity_oid?: string | null;
            /**
             * Workspaces
             * @default []
             */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    agents_v1_agents_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_prompt_v1_agents__name__prompt_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                /** @description Opt-in per-section provenance (i-045). When true, the response additionally carries 'sections' (source artifact, content hash, version, layer origin and tenant-overlay marker per composed section) and 'attribution' (declared|heuristic — how trustworthy the section map is; see the response model). The composed 'prompt' is byte-identical with or without the flag — explain never re-renders. */
                explain?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_v1_board_get: {
        parameters: {
            query: {
                /** @description A project's board_scope (e.g. dna-development). */
                scope: string;
                tenant?: string | null;
                recent?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_item_v1_board_item_get: {
        parameters: {
            query: {
                /** @description The project's board_scope. */
                scope: string;
                /** @description The work-item doc name (e.g. s-foo). */
                name: string;
                tenant?: string | null;
                /** @description Optional Kind hint (Story/Feature/…); probed if omitted. */
                kind?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_v1_insights_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                state?: string | null;
                /** @description Filter to one IntelSource's insights (a project shows only its own). Alias of source_ref; source_ref wins if both are set. */
                source?: string | null;
                source_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insight_metrics_v1_insights_metrics_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                source_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_insight_state_v1_insights__name__state_patch: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_insight_state_v1_insights__name__state_patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_v1_memories_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remember_memory_v1_memories_post: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_remember_memory_v1_memories_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RememberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_memories_v1_memories_import_post: {
        parameters: {
            query?: {
                scope?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * As
                     * @description passthrough = store the MIF verbatim only; native = project to a recallable Engram only; both = verbatim AND projected.
                     * @default both
                     * @enum {string}
                     */
                    as?: "passthrough" | "native" | "both";
                    /**
                     * Bundle
                     * @description The MIF payload: a JSON-LD {'@graph': [...]} bundle, a bare list of Memory Units, or a single Memory Unit.
                     */
                    bundle: unknown;
                    /**
                     * Dedupe
                     * @description id = skip a doc whose MIF id was already imported (idempotent re-import); content-hash = skip by exact content match; off = no pre-check.
                     * @default id
                     * @enum {string}
                     */
                    dedupe?: "id" | "content-hash" | "off";
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportMemoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personal_memories_v1_memories_personal_get: {
        parameters: {
            query?: {
                scope?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalMemoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_search_v1_memories_search_get: {
        parameters: {
            query: {
                q: string;
                scope?: string | null;
                tenant?: string | null;
                k?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__name__delete: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orgs_v1_orgs_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_v1_projects_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_create_project_v1_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_detail_v1_projects__slug__get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_members_v1_projects__slug__members_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                /** @description The signed-in user (email/id) — flags their own row and whether they may manage membership (Owner/Admin). */
                viewer?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_project_member_v1_projects__slug__members_post: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_project_member_v1_projects__slug__members_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_project_member_v1_projects__slug__members__user__delete: {
        parameters: {
            query?: {
                actor?: string | null;
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repos_v1_repos_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReposResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_v1_sources_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_tenant_owner_v1_tenants__tid__provision_owner_post: {
        parameters: {
            query?: {
                scope?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                tid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionTenantOwnerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_v1_tools_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_workspace_plan_v1_workspace_plan_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_put_workspace_plan_v1_workspace_plan_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_v1_workspaces_get: {
        parameters: {
            query?: {
                actor_oid?: string | null;
                actor_email?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_create_workspace_v1_workspaces_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invites_v1_workspaces_accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_accept_invites_v1_workspaces_accept_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInvitesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_v1_workspaces__workspace_id__invites_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_create_invite_v1_workspaces__workspace_id__invites_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_members_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: {
                actor_oid?: string | null;
                actor_email?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeWorkspaceMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionWorkspaceOwnerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
