/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agents
         * @description List a scope's prompt-target agents, tenant-aware.
         */
        get: operations["agents_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{name}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Prompt
         * @description Compose one agent's system prompt LIVE (Soul + Guardrails +
         *     instruction), tenant-aware — the per-tenant overlay a static emit
         *     artifact cannot express.
         */
        get: operations["agent_prompt_v1_agents__name__prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board
         * @description A compact SDLC summary for a project's ``board_scope``: Story + Feature
         *     counts by status, totals, and the newest work items — the console's board
         *     card. Reuses the shared SDLC read impl (``list_stories_impl``).
         */
        get: operations["board_v1_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board Item
         * @description One board work-item's FULL doc — the console's item-detail drawer:
         *     title, status, description, acceptance_criteria, definition_of_done,
         *     timeline, feature/epic refs, and produces. Delegates to the CORE
         *     ``board_item_impl`` (zero logic here). 404s an unknown name (for this
         *     scope/tenant, or under an explicit ``kind`` hint).
         */
        get: operations["board_item_v1_board_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insights
         * @description List the tenant's IntelInsight docs (ranked), optionally filtered by
         *     ``state`` and/or originating source. The console's per-project view
         *     passes ``?source=<name>`` so a project shows only its own insights.
         */
        get: operations["insights_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insight Metrics
         * @description The feedback KPIs (precision + noise rate) over the tenant's insight
         *     stream, optionally for one ``source_ref``. Read-only; the arithmetic is
         *     the core ``feedback_metrics``.
         */
        get: operations["insight_metrics_v1_insights_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights/{name}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Insight State
         * @description Set an insight's feedback state (new|actioned|dismissed|snoozed) —
         *     the reader's disposition. Delegates the read-modify-write to the core.
         */
        patch: operations["set_insight_state_v1_insights__name__state_patch"];
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories
         * @description List the tenant's memory — base + the tenant's OWN overlay (per the #83
         *     isolation), never another tenant's.
         */
        get: operations["memories_v1_memories_get"];
        put?: never;
        /**
         * Remember Memory
         * @description Persist ONE memory (a ``LessonLearned``) into the tenant's OWN overlay
         *     — the portal's ``remember`` / add affordance, tenant-scoped from the
         *     session (never base, never another tenant). Reuses the SAME CORE
         *     ``remember_impl`` the MCP ``remember`` tool delegates to (one core, three
         *     faces), so a memory added here is recalled identically by MCP/CLI. The
         *     deterministic ``_slug(summary)`` name it returns is the id the portal's
         *     ``DELETE /v1/memories/{name}`` targets to undo it.
         */
        post: operations["remember_memory_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories Search
         * @description Recall the tenant's memory for ``q`` (hybrid/bi-temporal when the
         *     search extra is present, honest lexical otherwise), tenant-scoped.
         */
        get: operations["memories_search_v1_memories_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Delete ONE memory from the tenant's OWN overlay — the portal's
         *     ownership/delete. Never base, never another tenant (a 404 otherwise).
         */
        delete: operations["delete_memory_v1_memories__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orgs
         * @description List the tenant's Organization docs (the console's top-level container).
         */
        get: operations["orgs_v1_orgs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects
         * @description List the tenant's Project docs (the multi-repo development-space
         *     containers the portfolio console aggregates).
         */
        get: operations["projects_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Detail
         * @description One project's detail + its RESOLVED repos (``repo_refs`` → the Repo
         *     docs). 404 when the slug is unknown for this (scope, tenant).
         */
        get: operations["project_detail_v1_projects__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Members
         * @description List a project's members with their RESOLVED role (highest-role-wins
         *     across org + project grants; org-owner a superuser), tenant-scoped. When
         *     ``viewer`` is set, reports ``viewer.can_manage`` so the portal gates its
         *     write controls. 404 when the slug is unknown for this (scope, tenant).
         */
        get: operations["project_members_v1_projects__slug__members_get"];
        put?: never;
        /**
         * Set Project Member
         * @description Invite / set a user's PROJECT-scope role — the Membros panel's write.
         *     RBAC-guarded: ``actor`` (the acting user) must be Owner/Admin of the
         *     project/org, and only an Owner may grant Owner (403 otherwise). Upserts the
         *     same Membership doc, tenant-scoped to the caller's overlay. 404 for an
         *     unknown project; 422 for an unknown role.
         */
        post: operations["set_project_member_v1_projects__slug__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Project Member
         * @description Remove a user's PROJECT-scope grant — the Membros panel's remove.
         *     RBAC-guarded: ``actor`` must be Owner/Admin (removing an Owner needs
         *     Owner). Deletes only the project-scope Membership (an inherited org grant
         *     is untouched), tenant-scoped. 403 without permission, 404 when the user has
         *     no project grant here.
         */
        delete: operations["remove_project_member_v1_projects__slug__members__user__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repos
         * @description List the tenant's Repo docs (code repositories the portfolio references).
         */
        get: operations["repos_v1_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description List the tenant's watched IntelSource docs (the Direction stage).
         */
        get: operations["sources_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Tenant Plan
         * @deprecated
         * @description DEPRECATED — use PUT /v1/workspace-plan. Accepts the legacy
         *     ``{tenant}`` body and writes it as the ``workspace_id`` (they are the same
         *     opaque string post-Model-B). 400 on a missing tenant/tier_id.
         */
        put: operations["put_tenant_plan_v1_tenant_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tid}/provision-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Tenant Owner
         * @description Ensure ``user`` is Owner of tenant ``tid`` when it has no Owner yet — the
         *     first-owner bootstrap. Idempotent (no-op if an Owner already exists).
         *     Returns the grants created (org-scope per referenced org + project-scope per
         *     orgless project). 400 on a missing tenant/user.
         */
        post: operations["provision_tenant_owner_v1_tenants__tid__provision_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tools
         * @description List a scope's Tool Kind surfaces (name + description), tenant-aware.
         */
        get: operations["tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Workspace Plan
         * @description Upsert the WorkspacePlan Kind assigning ``workspace_id`` → ``tier_id``
         *     (the billing→enforcement bridge). 400 on a missing workspace_id/tier_id.
         */
        put: operations["put_workspace_plan_v1_workspace_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invites
         * @description Accept every pending invite the caller's VERIFIED sign-in claims — binds
         *     the durable ``oid`` + flips ``pending→active``. Under config auth the
         *     claims come from the verified token (the invitee is still pending, so this
         *     route is exempt from the membership bind); under none/token a trusted portal
         *     passes the verified Entra claims. The SECURITY gate (verified email only, no
         *     hijack of a bound grant) is enforced in the core impl — never here.
         */
        post: operations["accept_invites_v1_workspaces_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invite
         * @description Invite an identity (by email) into a workspace — a ``pending``
         *     WorkspaceMembership. RBAC: the actor must be Owner/Admin (only an Owner may
         *     invite an Owner). 403 without permission; 422 on an unknown role.
         */
        post: operations["create_invite_v1_workspaces__workspace_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Members
         * @description List a workspace's members (grants). RBAC: the actor must be
         *     Owner/Admin. Under config auth the actor is the verified token identity;
         *     under none/token pass ``actor_oid``/``actor_email`` (the trusted portal
         *     vouches the session). 403 without permission.
         */
        get: operations["workspace_members_v1_workspaces__workspace_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Workspace Member
         * @description Revoke (remove) a member's WorkspaceMembership — the Members panel remove
         *     (issue ``i-033``). RBAC: the actor must be Owner/Admin (403 else). The LAST
         *     remaining owner can NEVER be revoked (409, fail-closed). A target holding no
         *     grant here is 404 (clear no-op). Target named by ``target_email`` or
         *     ``target_oid`` (oid wins). Under ``--auth config`` the actor is the verified
         *     token identity; under none/token the trusted portal passes ``actor`` claims.
         */
        post: operations["revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/provision-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Workspace Owner
         * @description Make the verified identity the OWNER of workspace ``{workspace_id}`` when
         *     it has no owner yet — the Model B first-login bootstrap. Idempotent: a
         *     re-call by the same identity is a no-op returning the membership; a later
         *     DIFFERENT user does not auto-escalate (``owner_exists`` no-op). ``{id}`` MUST
         *     equal the verified identity's ``tid`` (zero-migration; a cross-tid caller is
         *     403'd). 400 on a missing oid/email claim.
         */
        post: operations["provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_accept_invites_v1_workspaces_accept_post */
        Body_accept_invites_v1_workspaces_accept_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_create_invite_v1_workspaces__workspace_id__invites_post */
        Body_create_invite_v1_workspaces__workspace_id__invites_post: {
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post */
        Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post: {
            /** User */
            user: string;
        };
        /** Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post */
        Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_put_tenant_plan_v1_tenant_plan_put */
        Body_put_tenant_plan_v1_tenant_plan_put: {
            /**
             * Source
             * @default stripe
             */
            source: string;
            /** Status */
            status?: string | null;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
            /** Tenant */
            tenant: string;
            /** Tier Id */
            tier_id: string;
        };
        /** Body_put_workspace_plan_v1_workspace_plan_put */
        Body_put_workspace_plan_v1_workspace_plan_put: {
            /**
             * Source
             * @default stripe
             */
            source: string;
            /** Status */
            status?: string | null;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
            /** Tier Id */
            tier_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** Body_remember_memory_v1_memories_post */
        Body_remember_memory_v1_memories_post: {
            /**
             * Affect
             * @default triumph
             */
            affect: string;
            /**
             * Area
             * @default general
             */
            area: string;
            /**
             * Owner
             * @default portal
             */
            owner: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags?: string[] | null;
        };
        /** Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post */
        Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post: {
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
            /** Target Email */
            target_email?: string | null;
            /** Target Oid */
            target_oid?: string | null;
        };
        /** Body_set_insight_state_v1_insights__name__state_patch */
        Body_set_insight_state_v1_insights__name__state_patch: {
            /** State */
            state: string;
        };
        /** Body_set_project_member_v1_projects__slug__members_post */
        Body_set_project_member_v1_projects__slug__members_post: {
            /** Actor */
            actor?: string | null;
            /** Role */
            role: string;
            /** User */
            user: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agents_v1_agents_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_prompt_v1_agents__name__prompt_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_v1_board_get: {
        parameters: {
            query: {
                /** @description A project's board_scope (e.g. dna-development). */
                scope: string;
                tenant?: string | null;
                recent?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_item_v1_board_item_get: {
        parameters: {
            query: {
                /** @description The project's board_scope. */
                scope: string;
                /** @description The work-item doc name (e.g. s-foo). */
                name: string;
                tenant?: string | null;
                /** @description Optional Kind hint (Story/Feature/…); probed if omitted. */
                kind?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_v1_insights_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                state?: string | null;
                /** @description Filter to one IntelSource's insights (a project shows only its own). Alias of source_ref; source_ref wins if both are set. */
                source?: string | null;
                source_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insight_metrics_v1_insights_metrics_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                source_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_insight_state_v1_insights__name__state_patch: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_insight_state_v1_insights__name__state_patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_v1_memories_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remember_memory_v1_memories_post: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_remember_memory_v1_memories_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_search_v1_memories_search_get: {
        parameters: {
            query: {
                q: string;
                scope?: string | null;
                tenant?: string | null;
                k?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__name__delete: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orgs_v1_orgs_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_v1_projects_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_detail_v1_projects__slug__get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_members_v1_projects__slug__members_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                /** @description The signed-in user (email/id) — flags their own row and whether they may manage membership (Owner/Admin). */
                viewer?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_project_member_v1_projects__slug__members_post: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_project_member_v1_projects__slug__members_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_project_member_v1_projects__slug__members__user__delete: {
        parameters: {
            query?: {
                actor?: string | null;
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repos_v1_repos_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_v1_sources_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_tenant_plan_v1_tenant_plan_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_put_tenant_plan_v1_tenant_plan_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_tenant_owner_v1_tenants__tid__provision_owner_post: {
        parameters: {
            query?: {
                scope?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                tid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_v1_tools_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_workspace_plan_v1_workspace_plan_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_put_workspace_plan_v1_workspace_plan_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invites_v1_workspaces_accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_accept_invites_v1_workspaces_accept_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_v1_workspaces__workspace_id__invites_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_create_invite_v1_workspaces__workspace_id__invites_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_members_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: {
                actor_oid?: string | null;
                actor_email?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
