/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agents
         * @description List a scope's prompt-target agents, tenant-aware.
         */
        get: operations["agents_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{name}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Prompt
         * @description Compose one agent's system prompt LIVE (Soul + Guardrails +
         *     instruction), tenant-aware — the per-tenant overlay a static emit
         *     artifact cannot express.
         */
        get: operations["agent_prompt_v1_agents__name__prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board
         * @description A compact SDLC summary for a project's ``board_scope``: Story + Feature
         *     counts by status, totals, and the newest work items — the console's board
         *     card. Reuses the shared SDLC read impl (``list_stories_impl``).
         */
        get: operations["board_v1_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/board/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board Item
         * @description One board work-item's FULL doc — the console's item-detail drawer:
         *     title, status, description, acceptance_criteria, definition_of_done,
         *     timeline, feature/epic refs, and produces. Delegates to the CORE
         *     ``board_item_impl`` (zero logic here). 404s an unknown name (for this
         *     scope/tenant, or under an explicit ``kind`` hint).
         */
        get: operations["board_item_v1_board_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insights
         * @description List the tenant's IntelInsight docs (ranked), optionally filtered by
         *     ``state`` and/or originating source. The console's per-project view
         *     passes ``?source=<name>`` so a project shows only its own insights.
         */
        get: operations["insights_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insight Metrics
         * @description The feedback KPIs (precision + noise rate) over the tenant's insight
         *     stream, optionally for one ``source_ref``. Read-only; the arithmetic is
         *     the core ``feedback_metrics``.
         */
        get: operations["insight_metrics_v1_insights_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights/{name}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Insight State
         * @description Set an insight's feedback state (new|actioned|dismissed|snoozed) —
         *     the reader's disposition. Delegates the read-modify-write to the core.
         */
        patch: operations["set_insight_state_v1_insights__name__state_patch"];
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories
         * @description List the tenant's memory — base + the tenant's OWN overlay (per the #83
         *     isolation), never another tenant's.
         */
        get: operations["memories_v1_memories_get"];
        put?: never;
        /**
         * Remember Memory
         * @description Persist ONE memory (a ``LessonLearned``) into the tenant's OWN overlay
         *     — the portal's ``remember`` / add affordance, tenant-scoped from the
         *     session (never base, never another tenant). Reuses the SAME CORE
         *     ``remember_impl`` the MCP ``remember`` tool delegates to (one core, three
         *     faces), so a memory added here is recalled identically by MCP/CLI. The
         *     deterministic ``_slug(summary)`` name it returns is the id the portal's
         *     ``DELETE /v1/memories/{name}`` targets to undo it.
         */
        post: operations["remember_memory_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories Search
         * @description Recall the tenant's memory for ``q`` (hybrid/bi-temporal when the
         *     search extra is present, honest lexical otherwise), tenant-scoped.
         */
        get: operations["memories_search_v1_memories_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Delete ONE memory from the tenant's OWN overlay — the portal's
         *     ownership/delete. Never base, never another tenant (a 404 otherwise).
         */
        delete: operations["delete_memory_v1_memories__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orgs
         * @description List the tenant's Organization docs (the console's top-level container).
         */
        get: operations["orgs_v1_orgs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects
         * @description List the tenant's Project docs (the multi-repo development-space
         *     containers the portfolio console aggregates).
         */
        get: operations["projects_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Detail
         * @description One project's detail + its RESOLVED repos (``repo_refs`` → the Repo
         *     docs). 404 when the slug is unknown for this (scope, tenant).
         */
        get: operations["project_detail_v1_projects__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Members
         * @description List a project's members with their RESOLVED role (highest-role-wins
         *     across org + project grants; org-owner a superuser), tenant-scoped. When
         *     ``viewer`` is set, reports ``viewer.can_manage`` so the portal gates its
         *     write controls. 404 when the slug is unknown for this (scope, tenant).
         */
        get: operations["project_members_v1_projects__slug__members_get"];
        put?: never;
        /**
         * Set Project Member
         * @description Invite / set a user's PROJECT-scope role — the Membros panel's write.
         *     RBAC-guarded: ``actor`` (the acting user) must be Owner/Admin of the
         *     project/org, and only an Owner may grant Owner (403 otherwise). Upserts the
         *     same Membership doc, tenant-scoped to the caller's overlay. 404 for an
         *     unknown project; 422 for an unknown role.
         */
        post: operations["set_project_member_v1_projects__slug__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Project Member
         * @description Remove a user's PROJECT-scope grant — the Membros panel's remove.
         *     RBAC-guarded: ``actor`` must be Owner/Admin (removing an Owner needs
         *     Owner). Deletes only the project-scope Membership (an inherited org grant
         *     is untouched), tenant-scoped. 403 without permission, 404 when the user has
         *     no project grant here.
         */
        delete: operations["remove_project_member_v1_projects__slug__members__user__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repos
         * @description List the tenant's Repo docs (code repositories the portfolio references).
         */
        get: operations["repos_v1_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description List the tenant's watched IntelSource docs (the Direction stage).
         */
        get: operations["sources_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Tenant Plan
         * @deprecated
         * @description DEPRECATED — use PUT /v1/workspace-plan. Accepts the legacy
         *     ``{tenant}`` body and writes it as the ``workspace_id`` (they are the same
         *     opaque string post-Model-B). 400 on a missing tenant/tier_id.
         */
        put: operations["put_tenant_plan_v1_tenant_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tid}/provision-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Tenant Owner
         * @description Ensure ``user`` is Owner of tenant ``tid`` when it has no Owner yet — the
         *     first-owner bootstrap. Idempotent (no-op if an Owner already exists).
         *     Returns the grants created (org-scope per referenced org + project-scope per
         *     orgless project). 400 on a missing tenant/user.
         */
        post: operations["provision_tenant_owner_v1_tenants__tid__provision_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tools
         * @description List a scope's Tool Kind surfaces (name + description), tenant-aware.
         */
        get: operations["tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspace-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Workspace Plan
         * @description Upsert the WorkspacePlan Kind assigning ``workspace_id`` → ``tier_id``
         *     (the billing→enforcement bridge). 400 on a missing workspace_id/tier_id.
         */
        put: operations["put_workspace_plan_v1_workspace_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invites
         * @description Accept every pending invite the caller's VERIFIED sign-in claims — binds
         *     the durable ``oid`` + flips ``pending→active``. Under config auth the
         *     claims come from the verified token (the invitee is still pending, so this
         *     route is exempt from the membership bind); under none/token a trusted portal
         *     passes the verified Entra claims. The SECURITY gate (verified email only, no
         *     hijack of a bound grant) is enforced in the core impl — never here.
         */
        post: operations["accept_invites_v1_workspaces_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invite
         * @description Invite an identity (by email) into a workspace — a ``pending``
         *     WorkspaceMembership. RBAC: the actor must be Owner/Admin (only an Owner may
         *     invite an Owner). 403 without permission; 422 on an unknown role.
         */
        post: operations["create_invite_v1_workspaces__workspace_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Members
         * @description List a workspace's members (grants). RBAC: the actor must be
         *     Owner/Admin. Under config auth the actor is the verified token identity;
         *     under none/token pass ``actor_oid``/``actor_email`` (the trusted portal
         *     vouches the session). 403 without permission.
         */
        get: operations["workspace_members_v1_workspaces__workspace_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Workspace Member
         * @description Revoke (remove) a member's WorkspaceMembership — the Members panel remove
         *     (issue ``i-033``). RBAC: the actor must be Owner/Admin (403 else). The LAST
         *     remaining owner can NEVER be revoked (409, fail-closed). A target holding no
         *     grant here is 404 (clear no-op). Target named by ``target_email`` or
         *     ``target_oid`` (oid wins). Under ``--auth config`` the actor is the verified
         *     token identity; under none/token the trusted portal passes ``actor`` claims.
         */
        post: operations["revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/provision-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Workspace Owner
         * @description Make the verified identity the OWNER of workspace ``{workspace_id}`` when
         *     it has no owner yet — the Model B first-login bootstrap. Idempotent: a
         *     re-call by the same identity is a no-op returning the membership; a later
         *     DIFFERENT user does not auto-escalate (``owner_exists`` no-op). ``{id}`` MUST
         *     equal the verified identity's ``tid`` (zero-migration; a cross-tid caller is
         *     403'd). 400 on a missing oid/email claim.
         */
        post: operations["provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitesResponse */
        AcceptInvitesResponse: {
            /**
             * Accepted
             * @default []
             */
            accepted: components["schemas"]["AcceptedInvite"][];
            /** Identity Email */
            identity_email?: string | null;
            /** Identity Oid */
            identity_oid?: string | null;
        };
        /** AcceptedInvite */
        AcceptedInvite: {
            /**
             * Activated
             * @default false
             */
            activated: boolean;
            /** Role */
            role?: string | null;
            /** Workspace Id */
            workspace_id: string;
        };
        /** AgentPromptResponse */
        AgentPromptResponse: {
            /** Agent */
            agent: string;
            /** Model */
            model?: string | null;
            /** Prompt */
            prompt: string;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** AgentSummary */
        AgentSummary: {
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** AgentsResponse */
        AgentsResponse: {
            /** Agents */
            agents: components["schemas"]["AgentSummary"][];
            /** Scope */
            scope: string;
        };
        /**
         * BoardCounts
         * @description Status→count maps (dynamic keys — a status label is data).
         */
        BoardCounts: {
            /**
             * Features
             * @default {}
             */
            features: {
                [key: string]: number;
            };
            /**
             * Stories
             * @default {}
             */
            stories: {
                [key: string]: number;
            };
        };
        /**
         * BoardItemResponse
         * @description One SDLC work-item's full doc. The nested AC/DoD/timeline/produces lists
         *     pass through VERBATIM (the drawer renders them raw), so they stay loosely
         *     typed; ``business_value`` may be a label or a number → ``Any``.
         */
        BoardItemResponse: {
            /**
             * Acceptance Criteria
             * @default []
             */
            acceptance_criteria: unknown[];
            /** Business Value */
            business_value?: unknown | null;
            /** Closed At */
            closed_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Definition Of Done
             * @default []
             */
            definition_of_done: unknown[];
            /** Description */
            description?: string | null;
            /** Epic */
            epic?: string | null;
            /** Feature */
            feature?: string | null;
            /** Kind */
            kind: string;
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /** Name */
            name: string;
            /** Priority */
            priority?: string | null;
            /**
             * Produces
             * @default []
             */
            produces: unknown[];
            /** Reporter */
            reporter?: string | null;
            /** Scope */
            scope: string;
            /** Status */
            status?: string | null;
            /** Tenant */
            tenant?: string | null;
            /**
             * Timeline
             * @default []
             */
            timeline: {
                [key: string]: unknown;
            }[];
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** BoardListItem */
        BoardListItem: {
            /** Created At */
            created_at?: string | null;
            /** Kind */
            kind: string;
            /** Name */
            name?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
        };
        /** BoardResponse */
        BoardResponse: {
            counts: components["schemas"]["BoardCounts"];
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["BoardListItem"][];
            /**
             * Recent
             * @default []
             */
            recent: components["schemas"]["BoardListItem"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
            totals: components["schemas"]["BoardTotals"];
        };
        /** BoardTotals */
        BoardTotals: {
            /**
             * Features
             * @default 0
             */
            features: number;
            /**
             * Stories
             * @default 0
             */
            stories: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** Body_accept_invites_v1_workspaces_accept_post */
        Body_accept_invites_v1_workspaces_accept_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_create_invite_v1_workspaces__workspace_id__invites_post */
        Body_create_invite_v1_workspaces__workspace_id__invites_post: {
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post */
        Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post: {
            /** User */
            user: string;
        };
        /** Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post */
        Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post: {
            /** Claims */
            claims?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_put_tenant_plan_v1_tenant_plan_put */
        Body_put_tenant_plan_v1_tenant_plan_put: {
            /**
             * Source
             * @default stripe
             */
            source: string;
            /** Status */
            status?: string | null;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
            /** Tenant */
            tenant: string;
            /** Tier Id */
            tier_id: string;
        };
        /** Body_put_workspace_plan_v1_workspace_plan_put */
        Body_put_workspace_plan_v1_workspace_plan_put: {
            /**
             * Source
             * @default stripe
             */
            source: string;
            /** Status */
            status?: string | null;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
            /** Tier Id */
            tier_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** Body_remember_memory_v1_memories_post */
        Body_remember_memory_v1_memories_post: {
            /**
             * Affect
             * @default triumph
             */
            affect: string;
            /**
             * Area
             * @default general
             */
            area: string;
            /**
             * Owner
             * @default portal
             */
            owner: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags?: string[] | null;
        };
        /** Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post */
        Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post: {
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
            /** Target Email */
            target_email?: string | null;
            /** Target Oid */
            target_oid?: string | null;
        };
        /** Body_set_insight_state_v1_insights__name__state_patch */
        Body_set_insight_state_v1_insights__name__state_patch: {
            /** State */
            state: string;
        };
        /** Body_set_project_member_v1_projects__slug__members_post */
        Body_set_project_member_v1_projects__slug__members_post: {
            /** Actor */
            actor?: string | null;
            /** Role */
            role: string;
            /** User */
            user: string;
        };
        /** DeleteMemoryResponse */
        DeleteMemoryResponse: {
            /** Deleted */
            deleted: string;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
        };
        /** InsightMetricsResponse */
        InsightMetricsResponse: {
            /**
             * Actioned
             * @default 0
             */
            actioned: number;
            /**
             * Counts
             * @default {}
             */
            counts: {
                [key: string]: number;
            };
            /**
             * Dismissed
             * @default 0
             */
            dismissed: number;
            /** Noise Rate */
            noise_rate?: number | null;
            /** Precision */
            precision?: number | null;
            /** Scope */
            scope: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Tenant */
            tenant?: string | null;
        };
        /** InsightStateResponse */
        InsightStateResponse: {
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /** State */
            state: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Insights */
            insights: components["schemas"]["IntelInsightSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** IntelInsightSummary */
        IntelInsightSummary: {
            /** Action */
            action?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Evidence Rating */
            evidence_rating?: string | null;
            /** Fact */
            fact?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Pirs
             * @default []
             */
            pirs: string[];
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Source Ref */
            source_ref?: string | null;
            /**
             * State
             * @default new
             */
            state: string;
            /** Title */
            title?: string | null;
            /** Why */
            why?: string | null;
        };
        /** IntelSourceSummary */
        IntelSourceSummary: {
            /**
             * Cadence
             * @default weekly
             */
            cadence: string;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /** Name */
            name?: string | null;
            /**
             * Pirs
             * @default []
             */
            pirs: string[];
            /**
             * Threshold
             * @default 0.6
             */
            threshold: number;
            /** Type */
            type?: string | null;
        };
        /** InviteInfo */
        InviteInfo: {
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Identity Email */
            identity_email?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** InviteResponse */
        InviteResponse: {
            invite: components["schemas"]["InviteInfo"];
            /** Workspace Id */
            workspace_id: string;
        };
        /** MemoriesResponse */
        MemoriesResponse: {
            /** Memories */
            memories: components["schemas"]["MemorySummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** MemorySummary */
        MemorySummary: {
            /** Area */
            area?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** OrgSummary */
        OrgSummary: {
            /** Display Name */
            display_name?: string | null;
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** OrgsResponse */
        OrgsResponse: {
            /** Orgs */
            orgs: components["schemas"]["OrgSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** OwnerGrant */
        OwnerGrant: {
            /** Role */
            role: string;
            /** Scope Ref */
            scope_ref: string;
            /** Scope Type */
            scope_type: string;
        };
        /** ProjectDetailResponse */
        ProjectDetailResponse: {
            project: components["schemas"]["ProjectSummary"];
            /** Repos */
            repos: components["schemas"]["RepoSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** ProjectMemberSurface */
        ProjectMemberSurface: {
            /**
             * Is Org Owner
             * @default false
             */
            is_org_owner: boolean;
            /** Org Role */
            org_role?: string | null;
            /** Project Role */
            project_role?: string | null;
            /** Role */
            role: string;
            /** Role Display */
            role_display: string;
            /** Scope Note */
            scope_note?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** User */
            user: string;
            /**
             * You
             * @default false
             */
            you: boolean;
        };
        /** ProjectMemberViewer */
        ProjectMemberViewer: {
            /**
             * Can Manage
             * @default false
             */
            can_manage: boolean;
            /** Role */
            role?: string | null;
            /** User */
            user?: string | null;
        };
        /** ProjectMembersResponse */
        ProjectMembersResponse: {
            /** Members */
            members: components["schemas"]["ProjectMemberSurface"][];
            project: components["schemas"]["ProjectRef"];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
            viewer: components["schemas"]["ProjectMemberViewer"];
        };
        /** ProjectRef */
        ProjectRef: {
            /** Name */
            name?: string | null;
            /** Org Ref */
            org_ref?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Board Scope */
            board_scope?: string | null;
            /**
             * Intel Source Refs
             * @default []
             */
            intel_source_refs: string[];
            /** Name */
            name?: string | null;
            /** Org Ref */
            org_ref?: string | null;
            /**
             * Repo Refs
             * @default []
             */
            repo_refs: string[];
            /** Slug */
            slug?: string | null;
            /**
             * Visibility
             * @default private
             */
            visibility: string;
        };
        /** ProjectsResponse */
        ProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** ProvisionTenantOwnerResponse */
        ProvisionTenantOwnerResponse: {
            /**
             * Grants
             * @default []
             */
            grants: components["schemas"]["OwnerGrant"][];
            /** Provisioned */
            provisioned: boolean;
            /** Reason */
            reason?: string | null;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
            /** User */
            user: string;
        };
        /** ProvisionWorkspaceOwnerResponse */
        ProvisionWorkspaceOwnerResponse: {
            membership?: components["schemas"]["WorkspaceMemberSurface"] | null;
            /** Provisioned */
            provisioned: boolean;
            /** Reason */
            reason?: string | null;
            /**
             * Workspace Created
             * @default false
             */
            workspace_created: boolean;
            /** Workspace Id */
            workspace_id: string;
        };
        /**
         * RecallResponse
         * @description The recall envelope is typed; each ``hit`` stays a loose dict — its shape
         *     varies with the search plane active (lexical vs. hybrid/semantic add
         *     ``retention``/``semantic``/``rank_*`` keys), so it is honestly dynamic.
         */
        RecallResponse: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Hits
             * @default []
             */
            hits: {
                [key: string]: unknown;
            }[];
            /** Query */
            query: string;
            /** Scope */
            scope: string;
            /**
             * Semantic
             * @default false
             */
            semantic: boolean;
        };
        /** RememberResponse */
        RememberResponse: {
            /** Indexed */
            indexed: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** RemoveMemberResponse */
        RemoveMemberResponse: {
            /** Removed */
            removed: string;
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** RepoSummary */
        RepoSummary: {
            /** Default Branch */
            default_branch?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Provider
             * @default github
             */
            provider: string;
            /** Url */
            url?: string | null;
        };
        /** ReposResponse */
        ReposResponse: {
            /** Repos */
            repos: components["schemas"]["RepoSummary"][];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** RevokeWorkspaceMemberResponse */
        RevokeWorkspaceMemberResponse: {
            /** Revoked */
            revoked: boolean;
            target: components["schemas"]["WorkspaceMemberSurface"];
            /** Workspace Id */
            workspace_id: string;
        };
        /** SetMemberInfo */
        SetMemberInfo: {
            /** Role */
            role: string;
            /** Scope Ref */
            scope_ref: string;
            /** Scope Type */
            scope_type: string;
            /** Status */
            status: string;
            /** User */
            user: string;
        };
        /** SetMemberResponse */
        SetMemberResponse: {
            member: components["schemas"]["SetMemberInfo"];
            /** Scope */
            scope: string;
            /** Tenant */
            tenant?: string | null;
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Scope */
            scope: string;
            /** Sources */
            sources: components["schemas"]["IntelSourceSummary"][];
            /** Tenant */
            tenant?: string | null;
        };
        /** ToolSummary */
        ToolSummary: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name?: string | null;
        };
        /** ToolsResponse */
        ToolsResponse: {
            /** Scope */
            scope: string;
            /** Tools */
            tools: components["schemas"]["ToolSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceMemberSummary */
        WorkspaceMemberSummary: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Identity Email */
            identity_email?: string | null;
            /** Invited At */
            invited_at?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * WorkspaceMemberSurface
         * @description The ``_ws_member_surface`` projection (a superset of
         *     :class:`WorkspaceMemberSummary` with the ``workspace_id`` + ``identity_oid``).
         */
        WorkspaceMemberSurface: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Bound
             * @default false
             */
            bound: boolean;
            /** Identity Email */
            identity_email?: string | null;
            /** Identity Oid */
            identity_oid?: string | null;
            /** Invited At */
            invited_at?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /** WorkspaceMembersResponse */
        WorkspaceMembersResponse: {
            /** Members */
            members: components["schemas"]["WorkspaceMemberSummary"][];
            /** Workspace Id */
            workspace_id: string;
        };
        /** WorkspacePlanResponse */
        WorkspacePlanResponse: {
            /** Scope */
            scope: string;
            /** Status */
            status?: string | null;
            /** Tier Id */
            tier_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    agents_v1_agents_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_prompt_v1_agents__name__prompt_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_v1_board_get: {
        parameters: {
            query: {
                /** @description A project's board_scope (e.g. dna-development). */
                scope: string;
                tenant?: string | null;
                recent?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_item_v1_board_item_get: {
        parameters: {
            query: {
                /** @description The project's board_scope. */
                scope: string;
                /** @description The work-item doc name (e.g. s-foo). */
                name: string;
                tenant?: string | null;
                /** @description Optional Kind hint (Story/Feature/…); probed if omitted. */
                kind?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_v1_insights_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                state?: string | null;
                /** @description Filter to one IntelSource's insights (a project shows only its own). Alias of source_ref; source_ref wins if both are set. */
                source?: string | null;
                source_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insight_metrics_v1_insights_metrics_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                source_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_insight_state_v1_insights__name__state_patch: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_insight_state_v1_insights__name__state_patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_v1_memories_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remember_memory_v1_memories_post: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_remember_memory_v1_memories_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RememberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memories_search_v1_memories_search_get: {
        parameters: {
            query: {
                q: string;
                scope?: string | null;
                tenant?: string | null;
                k?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__name__delete: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orgs_v1_orgs_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_v1_projects_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_detail_v1_projects__slug__get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_members_v1_projects__slug__members_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
                /** @description The signed-in user (email/id) — flags their own row and whether they may manage membership (Owner/Admin). */
                viewer?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_project_member_v1_projects__slug__members_post: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_project_member_v1_projects__slug__members_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_project_member_v1_projects__slug__members__user__delete: {
        parameters: {
            query?: {
                actor?: string | null;
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repos_v1_repos_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReposResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_v1_sources_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_tenant_plan_v1_tenant_plan_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_put_tenant_plan_v1_tenant_plan_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_tenant_owner_v1_tenants__tid__provision_owner_post: {
        parameters: {
            query?: {
                scope?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                tid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_provision_tenant_owner_v1_tenants__tid__provision_owner_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionTenantOwnerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_v1_tools_get: {
        parameters: {
            query?: {
                scope?: string | null;
                tenant?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_workspace_plan_v1_workspace_plan_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_put_workspace_plan_v1_workspace_plan_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invites_v1_workspaces_accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_accept_invites_v1_workspaces_accept_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInvitesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_v1_workspaces__workspace_id__invites_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_create_invite_v1_workspaces__workspace_id__invites_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_members_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: {
                actor_oid?: string | null;
                actor_email?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_revoke_workspace_member_v1_workspaces__workspace_id__members_revoke_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeWorkspaceMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_provision_workspace_owner_v1_workspaces__workspace_id__provision_owner_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionWorkspaceOwnerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
