/**
 * s-parity-behavioral-harness — Composition-V2 behavioral parity fixtures.
 *
 * TypeScript executor of the SHARED fixture set at
 * `tests/parity-fixtures/composition/` (repo root). The Python twin
 * (`packages/sdk-py/tests/test_composition_parity_fixtures.py`) reads the
 * SAME case files; the frozen `expected/*.json` are GENERATED BY PYTHON (the
 * semantic reference) — this suite must match them byte-for-byte, gating the
 * TS Composition-V2 port (s-ts-composition-v2-port) on real behavior:
 * chain walk, rule lookup, tenant overlay, catalog splice, merges, provenance.
 *
 * Cases carrying `skip_ts: <reason>` are skipped here with the reason in the
 * test name (currently only the Catalog splice case — TS has no catalog
 * surface until i-185).
 *
 * Protocol per case: materialize `tree` as a real .dna-style filesystem tree
 * in a tmp dir, build a bare Kernel over a FilesystemSource, resolve
 * `target`, deep-compare
 *   { chain: computeResolutionChain(scope, tenant),
 *     resolved: resolveDocument(...).serialize() }
 * against the frozen JSON.
 */
import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import yaml from "js-yaml";
import { Kernel } from "../src/kernel/index.js";
import { FilesystemSource } from "../src/adapters/filesystem/source.js";

type Raw = Record<string, unknown>;

interface ParityCase {
  id?: string;
  title?: string;
  skip_ts?: string;
  target: { scope: string; kind: string; name: string; tenant?: string | null };
  tree?: {
    scopes?: Record<string, Raw[] | null>;
    tenants?: Record<string, Record<string, Raw[] | null>>;
  };
}

const FIXTURE_ROOT = join(
  import.meta.dir, "..", "..", "..", "tests", "parity-fixtures", "composition",
);
const CASE_DIR = join(FIXTURE_ROOT, "cases");
const EXPECTED_DIR = join(FIXTURE_ROOT, "expected");

function writeDoc(directory: string, doc: Raw, index: number): void {
  const meta = doc.metadata as Raw | undefined;
  const name = (meta?.name as string | undefined) ?? `doc-${index}`;
  const filename = `${String(doc.kind ?? "doc").toLowerCase()}-${name}.yaml`;
  writeFileSync(join(directory, filename), yaml.dump(doc), "utf-8");
}

/** Same layout contract as the Python executor's `_materialize`. */
function materialize(tree: NonNullable<ParityCase["tree"]>, base: string): void {
  for (const [scope, docs] of Object.entries(tree.scopes ?? {})) {
    const scopeDir = join(base, scope);
    mkdirSync(scopeDir, { recursive: true });
    (docs ?? []).forEach((doc, i) => writeDoc(scopeDir, doc, i));
  }
  for (const [tenant, scopes] of Object.entries(tree.tenants ?? {})) {
    for (const [scope, docs] of Object.entries(scopes ?? {})) {
      const overlayDir = join(base, "tenants", tenant, "scopes", scope);
      mkdirSync(overlayDir, { recursive: true });
      (docs ?? []).forEach((doc, i) => writeDoc(overlayDir, doc, i));
    }
  }
}

const caseFiles = readdirSync(CASE_DIR).filter((f) => f.endsWith(".yaml")).sort();

describe("composition parity fixtures (shared with sdk-py — Python output is frozen reference)", () => {
  test("fixture set present (>=10 shared cases)", () => {
    expect(caseFiles.length).toBeGreaterThanOrEqual(10);
  });

  for (const file of caseFiles) {
    const stem = file.replace(/\.yaml$/, "");
    const parityCase = yaml.load(
      readFileSync(join(CASE_DIR, file), "utf-8"),
    ) as ParityCase;

    if (parityCase.skip_ts) {
      test.skip(`${stem} — SKIP(ts): ${parityCase.skip_ts}`, () => {});
      continue;
    }

    test(stem, async () => {
      expect(parityCase.id).toBe(stem);
      const base = mkdtempSync(join(tmpdir(), "dna-parity-"));
      materialize(parityCase.tree ?? {}, base);

      const kernel = new Kernel();
      kernel.source(new FilesystemSource(base));

      const target = parityCase.target;
      const tenant = target.tenant ?? null;

      const chain = await kernel.computeResolutionChain(target.scope, tenant);
      const resolved = await kernel.resolveDocument(
        target.scope, target.kind, target.name, { tenant },
      );
      // JSON round-trip → plain arrays/objects, guaranteed JSON-clean compare.
      const actual = JSON.parse(JSON.stringify({
        chain,
        resolved: resolved.serialize(),
      }));

      const expectedPath = join(EXPECTED_DIR, `${stem}.json`);
      const expected = JSON.parse(readFileSync(expectedPath, "utf-8"));
      expect(actual).toEqual(expected);
    });
  }
});
