/**
 * rec-embedding-port — the deterministic zero-dep fake floor + kernel facade
 * (TS side).
 *
 * The FAKE is the offline/CI default `EmbeddingPort`: a stable, content-
 * addressed vector so the search plane has *something* deterministic to run
 * against without any ML dependency. Its defining property is BIT-EXACT Py↔TS
 * parity — enforced here (and in the Py twin `tests/test_fake_embedding.py`)
 * against the shared golden `tests/parity-fixtures/fake-embedding-golden.json`,
 * which is GENERATED by the Python `fake_embed_one`. This suite proving the TS
 * `fakeEmbedOne` reproduces it exactly IS the cross-language parity proof.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Kernel } from "../src/kernel/index.js";
import {
  FAKE_EMBEDDING_DIMS,
  FAKE_EMBEDDING_MODEL_ID,
  FakeEmbeddingProvider,
  fakeEmbedOne,
} from "../src/kernel/embedding.js";

const GOLDEN = JSON.parse(
  readFileSync(
    join(
      dirname(fileURLToPath(import.meta.url)),
      "../../../tests/parity-fixtures/fake-embedding-golden.json",
    ),
    "utf-8",
  ),
) as { model_id: string; dims: number; vectors: Record<string, number[]> };

describe("FakeEmbeddingProvider — deterministic zero-dep floor", () => {
  test("is deterministic and L2-normalized", () => {
    const a = fakeEmbedOne("the quick brown fox");
    const b = fakeEmbedOne("the quick brown fox");
    expect(a).toEqual(b);
    expect(a.length).toBe(FAKE_EMBEDDING_DIMS);
    const norm = Math.sqrt(a.reduce((s, x) => s + x * x, 0));
    expect(norm).toBeCloseTo(1.0, 12);
  });

  test("tokenizes to lowercase alphanumeric runs", () => {
    expect(fakeEmbedOne("Hello, WORLD!")).toEqual(fakeEmbedOne("hello world"));
  });

  test("empty / tokenless text is all-zeros", () => {
    const zeros = new Array(FAKE_EMBEDDING_DIMS).fill(0);
    expect(fakeEmbedOne("")).toEqual(zeros);
    expect(fakeEmbedOne("!!!  ...")).toEqual(zeros);
  });

  test("BIT-EXACT parity: reproduces the Py-generated golden vectors", () => {
    expect(GOLDEN.model_id).toBe(FAKE_EMBEDDING_MODEL_ID);
    expect(GOLDEN.dims).toBe(FAKE_EMBEDDING_DIMS);
    for (const [text, expected] of Object.entries(GOLDEN.vectors)) {
      // Strict equality: the doubles must be bit-identical to Python's.
      expect(fakeEmbedOne(text)).toEqual(expected);
    }
  });

  test("embed() preserves order; empty batch → empty", async () => {
    const prov = new FakeEmbeddingProvider();
    const texts = ["alpha", "beta", "gamma"];
    expect(await prov.embed(texts)).toEqual(texts.map((t) => fakeEmbedOne(t)));
    expect(await prov.embed([])).toEqual([]);
  });
});

describe("kernel.embed — fake floor + registered provider", () => {
  test("uses the fake floor by default", async () => {
    const k = new Kernel();
    expect(k.embeddingModelId).toBe(FAKE_EMBEDDING_MODEL_ID);
    expect(k.embeddingDims).toBe(FAKE_EMBEDDING_DIMS);
    expect(await k.embed(["the quick brown fox"])).toEqual([
      fakeEmbedOne("the quick brown fox"),
    ]);
    expect(await k.embed([])).toEqual([]);
  });

  test("a registered provider replaces the fake floor", async () => {
    const k = new Kernel();
    k.embeddingProvider({
      modelId: "stub-v1",
      dims: 2,
      async embed(texts: string[]) {
        return texts.map((t) => [t.length, 0]);
      },
    });
    expect(k.embeddingModelId).toBe("stub-v1");
    expect(k.embeddingDims).toBe(2);
    expect(await k.embed(["abc"])).toEqual([[3, 0]]);
  });

  test("withTenant shallow copies share the registered provider", async () => {
    const k = new Kernel({ tenant: "acme" });
    k.embeddingProvider({
      modelId: "stub-v1",
      dims: 1,
      async embed(texts: string[]) {
        return texts.map(() => [1]);
      },
    });
    const scoped = k.withTenant("other");
    expect(scoped.embeddingModelId).toBe("stub-v1");
    expect(await scoped.embed(["x"])).toEqual([[1]]);
  });
});
